// Code generated by tools/gen-go-api.py from sdk/abi.h. DO NOT EDIT.

package levilamina

/*
#include "sdk/abi.h"
#include "slots_gen.h"
#include "glue.h"
*/
import "C"

import (
	"runtime/cgo"
	"unsafe"
)

// RawAPI reaches every slot without a callback, typed in Go and gated: a slot the host lacks
// is a *NotProvidedError. A result means what abi.h says it means; the rest of the package
// builds the interpreted API on top of it. Use it through Raw.
type RawAPI struct{}

// Raw is the typed slot layer. Prefer the facades of this package where one exists.
var Raw RawAPI

var _ = unsafe.Pointer(nil)
var _ = cgo.Handle(0)

// Log calls the log slot.
//
// Log a message through the mod's own LeviLamina logger.
// level: -1=Off, 0=Fatal, 1=Error, 2=Warn, 3=Info, 4=Debug, 5=Trace
// (mirrors ll::io::LogLevel). Thread-safe.
func (RawAPI) Log(level int32, msg string) error {
	if api == nil || !bool(C.piergo_has_log(api)) {
		return notProvided("log")
	}
	C.piergo_call_log(api, self, C.int32_t(level), str(msg))
	return nil
}

// GamingStatus calls the gaming_status slot.
//
// Current gaming status: 0=Default, 1=Starting, 2=Running, 3=Stopping
// (mirrors ll::GamingStatus). Thread-safe.
func (RawAPI) GamingStatus() (int32, error) {
	if api == nil || !bool(C.piergo_has_gaming_status(api)) {
		return 0, notProvided("gaming_status")
	}
	r := C.piergo_call_gaming_status(api)
	return int32(r), nil
}

// UnsubscribeEvent calls the unsubscribe_event slot.
//
// Remove a listener previously returned by subscribe_event. Server thread only.
func (RawAPI) UnsubscribeEvent(listener ListenerHandle) (bool, error) {
	if api == nil || !bool(C.piergo_has_unsubscribe_event(api)) {
		return false, notProvided("unsubscribe_event")
	}
	r := C.piergo_call_unsubscribe_event(api, self, C.PierListenerHandle(listener.p))
	return bool(r), nil
}

// ListEvents calls the list_events slot.
//
// Enumerate all currently registered event ids. Server thread only.
func (RawAPI) ListEvents() ([]string, error) {
	if api == nil || !bool(C.piergo_has_list_events(api)) {
		return nil, notProvided("list_events")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_list_events(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// GetCurrentTick calls the get_current_tick slot.
//
// Current server tick (the tickID from Level::getCurrentTick()).
// Returns 0 when the level is not ready. Server thread only.
func (RawAPI) GetCurrentTick() (uint64, error) {
	if api == nil || !bool(C.piergo_has_get_current_tick(api)) {
		return 0, notProvided("get_current_tick")
	}
	r := C.piergo_call_get_current_tick(api)
	return uint64(r), nil
}

// GetTickDeltaTime calls the get_tick_delta_time slot.
//
// Wall-clock period of the last frame in seconds (mTickDeltaTime; 0.05 at 20
// TPS). It includes the sleep the server inserts to hold 20 Hz, so it is not
// the time spent computing a tick and its reciprocal is not a tick rate: it
// is one noisy sample of the frame rate. For TPS and MSPT use get_tps and
// get_mspt. Returns -1.0 if unavailable. Server thread only.
func (RawAPI) GetTickDeltaTime() (float64, error) {
	if api == nil || !bool(C.piergo_has_get_tick_delta_time(api)) {
		return 0, notProvided("get_tick_delta_time")
	}
	r := C.piergo_call_get_tick_delta_time(api)
	return float64(r), nil
}

// GetPlayerCount calls the get_player_count slot.
//
// Number of currently connected players
// (Level::getActivePlayerCount()). Server thread only.
func (RawAPI) GetPlayerCount() (int32, error) {
	if api == nil || !bool(C.piergo_has_get_player_count(api)) {
		return 0, notProvided("get_player_count")
	}
	r := C.piergo_call_get_player_count(api)
	return int32(r), nil
}

// GetSimPaused calls the get_sim_paused slot.
//
// Whether the simulation is currently paused
// (Level::getSimPaused()). Server thread only.
func (RawAPI) GetSimPaused() (bool, error) {
	if api == nil || !bool(C.piergo_has_get_sim_paused(api)) {
		return false, notProvided("get_sim_paused")
	}
	r := C.piergo_call_get_sim_paused(api)
	return bool(r), nil
}

// SpawnParticle calls the spawn_particle slot.
//
// Spawn a particle effect at a world coordinate. Used to outline a
// selection box edge-by-edge. Server thread only. Returns false if the
// level/dimension is not ready.
// dimension   : 0 = overworld, 1 = nether, 2 = the end.
// effect_name : e.g. "minecraft:basic_flame_particle" or
// "minecraft:redstone_wire_dust_particle".
func (RawAPI) SpawnParticle(dimension int32, effectName string, x float64, y float64, z float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_spawn_particle(api)) {
		return false, notProvided("spawn_particle")
	}
	r := C.piergo_call_spawn_particle(api, C.int32_t(dimension), str(effectName), C.double(x), C.double(y), C.double(z))
	return bool(r), nil
}

// GetPlayerPosition calls the get_player_position slot.
//
// Look up a connected player's feet position and dimension by name.
// Used to pick selection corners from where the player is standing.
// Server thread only.
func (RawAPI) GetPlayerPosition(name string) (PlayerPos, error) {
	if api == nil || !bool(C.piergo_has_get_player_position(api)) {
		return PlayerPos{}, notProvided("get_player_position")
	}
	r := C.piergo_call_get_player_position(api, str(name))
	return playerPosOf(r), nil
}

// SetBlock calls the set_block slot.
//
// Place a block natively (BlockSource::setBlock, DEFAULT update flags).
// block_spec = "minecraft:stone" / "stone" (default state) or a full
// {name,states,...} SNBT. Unknown names fail instead of placing a placeholder.
func (RawAPI) SetBlock(dim int32, x int32, y int32, z int32, blockSpec string) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_block(api)) {
		return false, notProvided("set_block")
	}
	r := C.piergo_call_set_block(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(blockSpec))
	return bool(r), nil
}

// GetTime calls the get_time slot.
//
// World time (Level::getTime).
func (RawAPI) GetTime() (int64, bool, error) {
	if api == nil || !bool(C.piergo_has_get_time(api)) {
		return 0, false, notProvided("get_time")
	}
	var o0 C.int64_t
	r := C.piergo_call_get_time(api, &o0)
	return int64(o0), bool(r), nil
}

// SetTime calls the set_time slot.
//
// Set world time natively (Level::setTime).
func (RawAPI) SetTime(t int64) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_time(api)) {
		return false, notProvided("set_time")
	}
	r := C.piergo_call_set_time(api, C.int64_t(t))
	return bool(r), nil
}

// SetWeather calls the set_weather slot.
//
// 0=clear 1=rain 2=thunder, native (Level::updateWeather).
func (RawAPI) SetWeather(weather int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_weather(api)) {
		return false, notProvided("set_weather")
	}
	r := C.piergo_call_set_weather(api, C.int32_t(weather))
	return bool(r), nil
}

// ListPlayers calls the list_players slot.
//
// One SNBT per online player: {name,xuid,uuid,dim,x,y,z}.
func (RawAPI) ListPlayers() ([]string, error) {
	if api == nil || !bool(C.piergo_has_list_players(api)) {
		return nil, notProvided("list_players")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_list_players(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// PlayerResolve calls the player_resolve slot.
//
// Resolve a player selector to their ActorUniqueID (bridges into the actor_* API).
func (RawAPI) PlayerResolve(sel PlayerSel) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_player_resolve(api)) {
		return 0, false, notProvided("player_resolve")
	}
	var o0 C.PierActorId
	r := C.piergo_call_player_resolve(api, sel.c(), &o0)
	return ActorID(o0), bool(r), nil
}

// PlayerSendMessage calls the player_send_message slot.
func (RawAPI) PlayerSendMessage(sel PlayerSel, msg string) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_send_message(api)) {
		return false, notProvided("player_send_message")
	}
	r := C.piergo_call_player_send_message(api, sel.c(), str(msg))
	return bool(r), nil
}

// PlayerDisconnect calls the player_disconnect slot.
func (RawAPI) PlayerDisconnect(sel PlayerSel, reason string) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_disconnect(api)) {
		return false, notProvided("player_disconnect")
	}
	r := C.piergo_call_player_disconnect(api, sel.c(), str(reason))
	return bool(r), nil
}

// BroadcastMessage calls the broadcast_message slot.
//
// sendMessage to every online player.
func (RawAPI) BroadcastMessage(msg string) error {
	if api == nil || !bool(C.piergo_has_broadcast_message(api)) {
		return notProvided("broadcast_message")
	}
	C.piergo_call_broadcast_message(api, str(msg))
	return nil
}

// PlayerSetGamemode calls the player_set_gamemode slot.
//
// 0=survival 1=creative 2=adventure 6=spectator, native (Player::setPlayerGameType).
func (RawAPI) PlayerSetGamemode(sel PlayerSel, mode int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_set_gamemode(api)) {
		return false, notProvided("player_set_gamemode")
	}
	r := C.piergo_call_player_set_gamemode(api, sel.c(), C.int32_t(mode))
	return bool(r), nil
}

// PlayerTeleport calls the player_teleport slot.
//
// Teleport natively (Actor::teleport). Custom dimensions (id >= 3) are allowed;
// the dimension bridge must produce an engine instance whose id matches, or the
// call fails instead of sending the player into a mismatched dimension.
func (RawAPI) PlayerTeleport(sel PlayerSel, dim int32, x float64, y float64, z float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_teleport(api)) {
		return false, notProvided("player_teleport")
	}
	r := C.piergo_call_player_teleport(api, sel.c(), C.int32_t(dim), C.double(x), C.double(y), C.double(z))
	return bool(r), nil
}

// PlayerGetNum calls the player_get_num slot.
//
// The four *_get_num slots share one convention. The return is whether the host has
// an answer, and *out is the answer; a false leaves *out untouched.
func (RawAPI) PlayerGetNum(sel PlayerSel, prop int32) (float64, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_num(api)) {
		return 0, false, notProvided("player_get_num")
	}
	var o0 C.double
	r := C.piergo_call_player_get_num(api, sel.c(), C.int32_t(prop), &o0)
	return float64(o0), bool(r), nil
}

// PlayerGetStr calls the player_get_str slot.
func (RawAPI) PlayerGetStr(sel PlayerSel, prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_str(api)) {
		return nil, false, notProvided("player_get_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_get_str(api, sel.c(), C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// PlayerSetNum calls the player_set_num slot.
func (RawAPI) PlayerSetNum(sel PlayerSel, prop int32, v float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_set_num(api)) {
		return false, notProvided("player_set_num")
	}
	r := C.piergo_call_player_set_num(api, sel.c(), C.int32_t(prop), C.double(v))
	return bool(r), nil
}

// PlayerAction calls the player_action slot.
func (RawAPI) PlayerAction(sel PlayerSel, action int32, sarg string, a float64, b float64, c float64) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_action(api)) {
		return nil, false, notProvided("player_action")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_action(api, sel.c(), C.int32_t(action), str(sarg), C.double(a), C.double(b), C.double(c), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorSnapshot calls the actor_snapshot slot.
//
// Full Actor::save NBT as SNBT.
func (RawAPI) ActorSnapshot(id ActorID) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_snapshot(api)) {
		return nil, false, notProvided("actor_snapshot")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_snapshot(api, C.PierActorId(id), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorGetNum calls the actor_get_num slot.
func (RawAPI) ActorGetNum(id ActorID, prop int32) (float64, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_num(api)) {
		return 0, false, notProvided("actor_get_num")
	}
	var o0 C.double
	r := C.piergo_call_actor_get_num(api, C.PierActorId(id), C.int32_t(prop), &o0)
	return float64(o0), bool(r), nil
}

// ActorGetStr calls the actor_get_str slot.
func (RawAPI) ActorGetStr(id ActorID, prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_str(api)) {
		return nil, false, notProvided("actor_get_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_get_str(api, C.PierActorId(id), C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorAction calls the actor_action slot.
func (RawAPI) ActorAction(id ActorID, action int32, sarg string, a float64, b float64, c float64) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_action(api)) {
		return nil, false, notProvided("actor_action")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_action(api, C.PierActorId(id), C.int32_t(action), str(sarg), C.double(a), C.double(b), C.double(c), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SpawnMob calls the spawn_mob slot.
//
// Spawn a mob (Spawner::spawnMob); on success *out = its ActorUniqueID.
func (RawAPI) SpawnMob(dim int32, typeName string, x float64, y float64, z float64) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_spawn_mob(api)) {
		return 0, false, notProvided("spawn_mob")
	}
	var o0 C.PierActorId
	r := C.piergo_call_spawn_mob(api, C.int32_t(dim), str(typeName), C.double(x), C.double(y), C.double(z), &o0)
	return ActorID(o0), bool(r), nil
}

// Explode calls the explode slot.
//
// Level::explode. source may be 0 (no source actor).
func (RawAPI) Explode(dim int32, x float64, y float64, z float64, radius float32, maxResistance float32, source ActorID, fire bool, breaksBlocks bool, allowUnderwater bool) (bool, error) {
	if api == nil || !bool(C.piergo_has_explode(api)) {
		return false, notProvided("explode")
	}
	r := C.piergo_call_explode(api, C.int32_t(dim), C.double(x), C.double(y), C.double(z), C.float(radius), C.float(maxResistance), C.PierActorId(source), C.bool(fire), C.bool(breaksBlocks), C.bool(allowUnderwater))
	return bool(r), nil
}

// BlockGetNum calls the block_get_num slot.
//
// §D blocks & block entities
func (RawAPI) BlockGetNum(dim int32, x int32, y int32, z int32, prop int32) (float64, bool, error) {
	if api == nil || !bool(C.piergo_has_block_get_num(api)) {
		return 0, false, notProvided("block_get_num")
	}
	var o0 C.double
	r := C.piergo_call_block_get_num(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), C.int32_t(prop), &o0)
	return float64(o0), bool(r), nil
}

// BlockGetStr calls the block_get_str slot.
func (RawAPI) BlockGetStr(dim int32, x int32, y int32, z int32, prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_block_get_str(api)) {
		return nil, false, notProvided("block_get_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_block_get_str(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// BlockAction calls the block_action slot.
func (RawAPI) BlockAction(dim int32, x int32, y int32, z int32, action int32, sarg string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_block_action(api)) {
		return nil, false, notProvided("block_action")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_block_action(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), C.int32_t(action), str(sarg), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// BlockEntitySnbt calls the block_entity_snbt slot.
//
// BlockActor::save (with default SaveContext) as SNBT; false if none there.
func (RawAPI) BlockEntitySnbt(dim int32, x int32, y int32, z int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_block_entity_snbt(api)) {
		return nil, false, notProvided("block_entity_snbt")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_block_entity_snbt(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ItemGetNum calls the item_get_num slot.
//
// §E items (SNBT value objects) & containers
func (RawAPI) ItemGetNum(itemSnbt string, prop int32) (float64, bool, error) {
	if api == nil || !bool(C.piergo_has_item_get_num(api)) {
		return 0, false, notProvided("item_get_num")
	}
	var o0 C.double
	r := C.piergo_call_item_get_num(api, str(itemSnbt), C.int32_t(prop), &o0)
	return float64(o0), bool(r), nil
}

// ItemGetStr calls the item_get_str slot.
func (RawAPI) ItemGetStr(itemSnbt string, prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_item_get_str(api)) {
		return nil, false, notProvided("item_get_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_item_get_str(api, str(itemSnbt), C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ItemTransform calls the item_transform slot.
//
// Rebuild → mutate → serialize; out receives the NEW item SNBT.
func (RawAPI) ItemTransform(itemSnbt string, op int32, sarg string, narg float64) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_item_transform(api)) {
		return nil, false, notProvided("item_transform")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_item_transform(api, str(itemSnbt), C.int32_t(op), str(sarg), C.double(narg), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ContainerSize calls the container_size slot.
func (RawAPI) ContainerSize(ref ContainerRef) (int32, bool, error) {
	if api == nil || !bool(C.piergo_has_container_size(api)) {
		return 0, false, notProvided("container_size")
	}
	var o0 C.int32_t
	r := C.piergo_call_container_size(api, ref.c(), &o0)
	return int32(o0), bool(r), nil
}

// ContainerGetItem calls the container_get_item slot.
//
// Slot content as item SNBT (empty slots yield the air item's SNBT).
func (RawAPI) ContainerGetItem(ref ContainerRef, slot int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_container_get_item(api)) {
		return nil, false, notProvided("container_get_item")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_container_get_item(api, ref.c(), C.int32_t(slot), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ContainerSetItem calls the container_set_item slot.
func (RawAPI) ContainerSetItem(ref ContainerRef, slot int32, itemSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_container_set_item(api)) {
		return false, notProvided("container_set_item")
	}
	r := C.piergo_call_container_set_item(api, ref.c(), C.int32_t(slot), str(itemSnbt))
	return bool(r), nil
}

// ContainerAddItem calls the container_add_item slot.
func (RawAPI) ContainerAddItem(ref ContainerRef, itemSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_container_add_item(api)) {
		return false, notProvided("container_add_item")
	}
	r := C.piergo_call_container_add_item(api, ref.c(), str(itemSnbt))
	return bool(r), nil
}

// ContainerRemoveItem calls the container_remove_item slot.
func (RawAPI) ContainerRemoveItem(ref ContainerRef, slot int32, count int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_container_remove_item(api)) {
		return false, notProvided("container_remove_item")
	}
	r := C.piergo_call_container_remove_item(api, ref.c(), C.int32_t(slot), C.int32_t(count))
	return bool(r), nil
}

// ContainerClear calls the container_clear slot.
func (RawAPI) ContainerClear(ref ContainerRef) (bool, error) {
	if api == nil || !bool(C.piergo_has_container_clear(api)) {
		return false, notProvided("container_clear")
	}
	r := C.piergo_call_container_clear(api, ref.c())
	return bool(r), nil
}

// ScoreboardOp calls the scoreboard_op slot.
//
// §F scoreboard
func (RawAPI) ScoreboardOp(op int32, a string, b string, n int64) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_scoreboard_op(api)) {
		return nil, false, notProvided("scoreboard_op")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_scoreboard_op(api, C.int32_t(op), str(a), str(b), C.int64_t(n), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// RegisterCommandEnum calls the register_command_enum slot.
//
// values_snbt = {values:[["name",1L],…]}  → tryRegisterRuntimeEnum.
func (RawAPI) RegisterCommandEnum(name string, valuesSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_register_command_enum(api)) {
		return false, notProvided("register_command_enum")
	}
	r := C.piergo_call_register_command_enum(api, str(name), str(valuesSnbt))
	return bool(r), nil
}

// RegisterCommandSoftEnum calls the register_command_soft_enum slot.
//
// values_snbt = {values:["a","b"]}         → tryRegisterSoftEnum.
func (RawAPI) RegisterCommandSoftEnum(name string, valuesSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_register_command_soft_enum(api)) {
		return false, notProvided("register_command_soft_enum")
	}
	r := C.piergo_call_register_command_soft_enum(api, str(name), str(valuesSnbt))
	return bool(r), nil
}

// UpdateCommandSoftEnum calls the update_command_soft_enum slot.
//
// op: 0=set 1=add 2=remove.
func (RawAPI) UpdateCommandSoftEnum(name string, op int32, valuesSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_update_command_soft_enum(api)) {
		return false, notProvided("update_command_soft_enum")
	}
	r := C.piergo_call_update_command_soft_enum(api, str(name), C.int32_t(op), str(valuesSnbt))
	return bool(r), nil
}

// NbtBinaryToSnbt calls the nbt_binary_to_snbt slot.
func (RawAPI) NbtBinaryToSnbt(data []byte, fmt int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_nbt_binary_to_snbt(api)) {
		return nil, false, notProvided("nbt_binary_to_snbt")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_nbt_binary_to_snbt(api, bytesPtr(data), C.size_t(len(data)), C.int32_t(fmt), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// KvdbOpen calls the kvdb_open slot.
//
// KvDb: THREAD-SAFE (internal mutex). Paths are confined to the mod's
// own data directory; ".." and absolute paths are rejected. Handles are
// owned by the loader and force-closed (with a warning) at mod unload.
func (RawAPI) KvdbOpen(path string, createIfMissing bool) (KvDbHandle, error) {
	if api == nil || !bool(C.piergo_has_kvdb_open(api)) {
		return KvDbHandle{}, notProvided("kvdb_open")
	}
	r := C.piergo_call_kvdb_open(api, self, str(path), C.bool(createIfMissing))
	return KvDbHandle{p: unsafe.Pointer(r)}, nil
}

// KvdbClose calls the kvdb_close slot.
func (RawAPI) KvdbClose(hArg KvDbHandle) error {
	if api == nil || !bool(C.piergo_has_kvdb_close(api)) {
		return notProvided("kvdb_close")
	}
	C.piergo_call_kvdb_close(api, C.PierKvDbHandle(hArg.p))
	return nil
}

// KvdbGet calls the kvdb_get slot.
func (RawAPI) KvdbGet(hArg KvDbHandle, key string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_kvdb_get(api)) {
		return nil, false, notProvided("kvdb_get")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_kvdb_get(api, C.PierKvDbHandle(hArg.p), str(key), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// KvdbSet calls the kvdb_set slot.
func (RawAPI) KvdbSet(hArg KvDbHandle, key string, value string) (bool, error) {
	if api == nil || !bool(C.piergo_has_kvdb_set(api)) {
		return false, notProvided("kvdb_set")
	}
	r := C.piergo_call_kvdb_set(api, C.PierKvDbHandle(hArg.p), str(key), str(value))
	return bool(r), nil
}

// KvdbDel calls the kvdb_del slot.
func (RawAPI) KvdbDel(hArg KvDbHandle, key string) (bool, error) {
	if api == nil || !bool(C.piergo_has_kvdb_del(api)) {
		return false, notProvided("kvdb_del")
	}
	r := C.piergo_call_kvdb_del(api, C.PierKvDbHandle(hArg.p), str(key))
	return bool(r), nil
}

// KvdbHas calls the kvdb_has slot.
func (RawAPI) KvdbHas(hArg KvDbHandle, key string) (bool, error) {
	if api == nil || !bool(C.piergo_has_kvdb_has(api)) {
		return false, notProvided("kvdb_has")
	}
	r := C.piergo_call_kvdb_has(api, C.PierKvDbHandle(hArg.p), str(key))
	return bool(r), nil
}

// KvdbIsEmpty calls the kvdb_is_empty slot.
func (RawAPI) KvdbIsEmpty(hArg KvDbHandle) (bool, error) {
	if api == nil || !bool(C.piergo_has_kvdb_is_empty(api)) {
		return false, notProvided("kvdb_is_empty")
	}
	r := C.piergo_call_kvdb_is_empty(api, C.PierKvDbHandle(hArg.p))
	return bool(r), nil
}

// SysInfoStr calls the sys_info_str slot.
//
// System info: THREAD-SAFE (plain OS calls).
func (RawAPI) SysInfoStr(prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_sys_info_str(api)) {
		return nil, false, notProvided("sys_info_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_sys_info_str(api, C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SysGetEnv calls the sys_get_env slot.
func (RawAPI) SysGetEnv(name string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_sys_get_env(api)) {
		return nil, false, notProvided("sys_get_env")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_sys_get_env(api, str(name), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SysSetEnv calls the sys_set_env slot.
func (RawAPI) SysSetEnv(name string, value string) (bool, error) {
	if api == nil || !bool(C.piergo_has_sys_set_env(api)) {
		return false, notProvided("sys_set_env")
	}
	r := C.piergo_call_sys_set_env(api, str(name), str(value))
	return bool(r), nil
}

// SysIsWine calls the sys_is_wine slot.
func (RawAPI) SysIsWine() (bool, error) {
	if api == nil || !bool(C.piergo_has_sys_is_wine(api)) {
		return false, notProvided("sys_is_wine")
	}
	r := C.piergo_call_sys_is_wine(api)
	return bool(r), nil
}

// GetDifficulty calls the get_difficulty slot.
//
// Server / world-level settings.
func (RawAPI) GetDifficulty() (int32, bool, error) {
	if api == nil || !bool(C.piergo_has_get_difficulty(api)) {
		return 0, false, notProvided("get_difficulty")
	}
	var o0 C.int32_t
	r := C.piergo_call_get_difficulty(api, &o0)
	return int32(o0), bool(r), nil
}

// SetDifficulty calls the set_difficulty slot.
func (RawAPI) SetDifficulty(d int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_difficulty(api)) {
		return false, notProvided("set_difficulty")
	}
	r := C.piergo_call_set_difficulty(api, C.int32_t(d))
	return bool(r), nil
}

// GetSeed calls the get_seed slot.
func (RawAPI) GetSeed() (int64, bool, error) {
	if api == nil || !bool(C.piergo_has_get_seed(api)) {
		return 0, false, notProvided("get_seed")
	}
	var o0 C.int64_t
	r := C.piergo_call_get_seed(api, &o0)
	return int64(o0), bool(r), nil
}

// GameRuleGet calls the game_rule_get slot.
//
// out sink receives SNBT {type:"bool"|"int"|"float", value:…}; false if unknown rule.
func (RawAPI) GameRuleGet(name string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_game_rule_get(api)) {
		return nil, false, notProvided("game_rule_get")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_game_rule_get(api, str(name), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// GameRuleSet calls the game_rule_set slot.
func (RawAPI) GameRuleSet(name string, value string) (bool, error) {
	if api == nil || !bool(C.piergo_has_game_rule_set(api)) {
		return false, notProvided("game_rule_set")
	}
	r := C.piergo_call_game_rule_set(api, str(name), str(value))
	return bool(r), nil
}

// ServerInfoStr calls the server_info_str slot.
func (RawAPI) ServerInfoStr(prop int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_server_info_str(api)) {
		return nil, false, notProvided("server_info_str")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_server_info_str(api, C.int32_t(prop), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SpawnParticleFor calls the spawn_particle_for slot.
//
// Per-player particle packet (additive, gated by struct_size).
// Sends a SpawnParticleEffectPacket ONLY to the resolved player
// (Player::sendNetworkPacket) instead of Level::spawnParticleEffect's
// dimension-wide broadcast — other clients never receive it.
// `dimension` is the vanilla dimension id carried in the packet; pass the
// dimension the coordinates refer to (normally the player's own — clients
// don't render particles for another dimension).
// False if the player is offline / can't be resolved.
func (RawAPI) SpawnParticleFor(sel PlayerSel, dimension int32, effectName string, x float64, y float64, z float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_spawn_particle_for(api)) {
		return false, notProvided("spawn_particle_for")
	}
	r := C.piergo_call_spawn_particle_for(api, sel.c(), C.int32_t(dimension), str(effectName), C.double(x), C.double(y), C.double(z))
	return bool(r), nil
}

// SendPacket calls the send_packet slot.
//
// Raw per-connection packet send (additive, gated by struct_size) — the
// generic primitive spawn_particle_for derives from.
// `packet_id` is a MinecraftPacketIds value; `body`/`body_len` is the
// packet's wire-format body for the CURRENT game version. The bridge
// deserializes it into a real packet object (MinecraftPackets::createPacket
// + Packet::read) and delivers it to the resolved player's connection only.
// False if: player offline, unknown/unconstructible id, body fails to
// parse, or bytes are left over after parsing (wrong shape for this
// version). ESCAPE HATCH: the wire format is version-specific and is the
// caller's responsibility; prefer typed entries when one exists.
func (RawAPI) SendPacket(sel PlayerSel, packetId int32, body []byte) (bool, error) {
	if api == nil || !bool(C.piergo_has_send_packet(api)) {
		return false, notProvided("send_packet")
	}
	r := C.piergo_call_send_packet(api, sel.c(), C.int32_t(packetId), bytesPtr(body), C.size_t(len(body)))
	return bool(r), nil
}

// TickFreeze calls the tick_freeze slot.
//
// Tick control (additive, gated by struct_size). Backed by a bridge-owned
// detour on Level::tick, installed lazily on the first control call and
// left in place (idle cost: one predictable branch per frame — a control
// call can arrive from a command handler that is executing INSIDE the
// tick, where unpatching would not be safe). Server thread only.
// While frozen, mobs/blocks/redstone/time stop; players can still move
// and chat (movement is client-authoritative, network runs outside the
// level tick).
func (RawAPI) TickFreeze(on bool) (bool, error) {
	if api == nil || !bool(C.piergo_has_tick_freeze(api)) {
		return false, notProvided("tick_freeze")
	}
	r := C.piergo_call_tick_freeze(api, C.bool(on))
	return bool(r), nil
}

// TickStep calls the tick_step slot.
//
// Only while frozen: queue exactly n extra frames. False if not frozen or n == 0.
func (RawAPI) TickStep(n uint32) (bool, error) {
	if api == nil || !bool(C.piergo_has_tick_step(api)) {
		return false, notProvided("tick_step")
	}
	r := C.piergo_call_tick_step(api, C.uint32_t(n))
	return bool(r), nil
}

// TickWarp calls the tick_warp slot.
//
// 0 < factor <= 100. Fractional = slow motion (accumulator), 1.0 restores normal.
func (RawAPI) TickWarp(factor float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_tick_warp(api)) {
		return false, notProvided("tick_warp")
	}
	r := C.piergo_call_tick_warp(api, C.double(factor))
	return bool(r), nil
}

// ProfileBegin calls the profile_begin slot.
//
// Arm a window of `ticks` level ticks (1..12000). False if 0, too big, or already sampling.
func (RawAPI) ProfileBegin(ticks uint32) (bool, error) {
	if api == nil || !bool(C.piergo_has_profile_begin(api)) {
		return false, notProvided("profile_begin")
	}
	r := C.piergo_call_profile_begin(api, C.uint32_t(ticks))
	return bool(r), nil
}

// ProfileTake calls the profile_take slot.
//
// Poll for the finished report. False while sampling / nothing armed;
// true exactly once per window, sinking one SNBT report:
// {ticks:N, buckets:{level_tick:{us,calls}, dimension_tick:{…}, redstone:{…},
// chunk_blocks:{…}, block_entities:{…}}}. Bucket times are INCLUSIVE
// (nested subsystems), report side by side, don't sum.
func (RawAPI) ProfileTake() ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_profile_take(api)) {
		return nil, false, notProvided("profile_take")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_profile_take(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SimSpawn calls the sim_spawn slot.
//
// Simulated ("fake") players (additive, gated by struct_size).
// sim_spawn creates a real ServerPlayer with that name — every existing
// per-player entry (teleport, health, inventory, kick,…) works on it via
// the usual name selector. sim_do multiplexes the simulate* verb family:
// the action vocabulary grows bridge-side without new table slots
// (verbs: despawn stop jump attack interact use_item drop respawn
// move_to navigate_to look_at destroy_block destroy_look stop_destroy
// interact_block sneak fly chat — args as SNBT, see docs). Gated on
// isSimulatedPlayer(): a real player can never be puppeted. False on
// unknown verb, malformed args, offline/non-sim target.
func (RawAPI) SimSpawn(name string, dimension int32, x float64, y float64, z float64) (bool, error) {
	if api == nil || !bool(C.piergo_has_sim_spawn(api)) {
		return false, notProvided("sim_spawn")
	}
	r := C.piergo_call_sim_spawn(api, str(name), C.int32_t(dimension), C.double(x), C.double(y), C.double(z))
	return bool(r), nil
}

// SimDo calls the sim_do slot.
func (RawAPI) SimDo(sel PlayerSel, action string, argsSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_sim_do(api)) {
		return false, notProvided("sim_do")
	}
	r := C.piergo_call_sim_do(api, sel.c(), str(action), str(argsSnbt))
	return bool(r), nil
}

// SimIs calls the sim_is slot.
//
// True if the selector resolves to a live simulated player. Lets a mod
// re-validate a bot after a restart (the SimulatedPlayer persists in the
// world, but in-memory handles don't).
func (RawAPI) SimIs(sel PlayerSel) (bool, error) {
	if api == nil || !bool(C.piergo_has_sim_is(api)) {
		return false, notProvided("sim_is")
	}
	r := C.piergo_call_sim_is(api, sel.c())
	return bool(r), nil
}

// SimList calls the sim_list slot.
//
// Enumerate the names of all live simulated players (sink receives each
// name). Rebuild a handle from a name to drive a bot that outlived the
// session that spawned it.
func (RawAPI) SimList() ([]string, error) {
	if api == nil || !bool(C.piergo_has_sim_list(api)) {
		return nil, notProvided("sim_list")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_sim_list(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// Villages calls the villages slot.
//
// Enumerate villages in a dimension. Each: {uuid, center:[x,y,z],
// bounds:{min,max}, poi_count}.
func (RawAPI) Villages(dimension int32) ([]string, error) {
	if api == nil || !bool(C.piergo_has_villages(api)) {
		return nil, notProvided("villages")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_villages(api, C.int32_t(dimension), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// StructuresNear calls the structures_near slot.
//
// Hardcoded spawn areas (nether fortress / witch hut / ocean monument /
// pillager outpost) whose chunks intersect a radius around (x,y,z). Each:
// {type, bounds:{min,max}}. Only LOADED chunks are inspected — a
// read-only query never force-loads.
func (RawAPI) StructuresNear(dimension int32, x int32, y int32, z int32, radius int32) ([]string, error) {
	if api == nil || !bool(C.piergo_has_structures_near(api)) {
		return nil, notProvided("structures_near")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_structures_near(api, C.int32_t(dimension), C.int32_t(x), C.int32_t(y), C.int32_t(z), C.int32_t(radius), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// PlayerSendMessageTyped calls the player_send_message_typed slot.
//
// Send a message of a specific TextPacketType to one player (additive,
// gated by struct_size). `type` is a TextPacketType value:
// 0 Raw · 1 Chat · 2 Translate · 3 Popup · 4 JukeboxPopup · 5 Tip ·
// 6 SystemMessage · 7 Whisper · 8 Announcement · 9 TextObjectWhisper ·
// 10 TextObject · 11 TextObjectAnnouncement.
// Out-of-range falls back to Raw. Single-string body (like LSE tell): the
// author/param kinds (Chat/Whisper/Translate) arrive as plain text.
// plain `player_send_message` remains the Raw/Chat convenience path.
func (RawAPI) PlayerSendMessageTyped(sel PlayerSel, msg string, typeArg int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_send_message_typed(api)) {
		return false, notProvided("player_send_message_typed")
	}
	r := C.piergo_call_player_send_message_typed(api, sel.c(), str(msg), C.int32_t(typeArg))
	return bool(r), nil
}

// GetMoney calls the get_money slot.
//
// Balance. Returns -1 on failure (empty xuid, database error, or absent
// backend); a real balance is never negative, so < 0 means "cannot say".
// Note that it opens an account at the configured default for an unseen
// xuid, so this is not a side-effect-free read.
func (RawAPI) GetMoney(xuid string) (int64, error) {
	if api == nil || !bool(C.piergo_has_get_money(api)) {
		return 0, notProvided("get_money")
	}
	r := C.piergo_call_get_money(api, str(xuid))
	return int64(r), nil
}

// SetMoney calls the set_money slot.
//
// Set to money, which is a target balance rather than a delta.
func (RawAPI) SetMoney(xuid string, money int64) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_money(api)) {
		return false, notProvided("set_money")
	}
	r := C.piergo_call_set_money(api, str(xuid), C.int64_t(money))
	return bool(r), nil
}

// AddMoney calls the add_money slot.
func (RawAPI) AddMoney(xuid string, money int64) (bool, error) {
	if api == nil || !bool(C.piergo_has_add_money(api)) {
		return false, notProvided("add_money")
	}
	r := C.piergo_call_add_money(api, str(xuid), C.int64_t(money))
	return bool(r), nil
}

// ReduceMoney calls the reduce_money slot.
func (RawAPI) ReduceMoney(xuid string, money int64) (bool, error) {
	if api == nil || !bool(C.piergo_has_reduce_money(api)) {
		return false, notProvided("reduce_money")
	}
	r := C.piergo_call_reduce_money(api, str(xuid), C.int64_t(money))
	return bool(r), nil
}

// TransMoney calls the trans_money slot.
//
// An empty from or to means created from or destroyed into nothing. What the
// payee receives is reduced by pay_tax (see above). from == to fails.
func (RawAPI) TransMoney(from string, to string, val int64, note string) (bool, error) {
	if api == nil || !bool(C.piergo_has_trans_money(api)) {
		return false, notProvided("trans_money")
	}
	r := C.piergo_call_trans_money(api, str(from), str(to), C.int64_t(val), str(note))
	return bool(r), nil
}

// MoneyGetHist calls the money_get_hist slot.
func (RawAPI) MoneyGetHist(xuid string, timediff int32) ([]string, error) {
	if api == nil || !bool(C.piergo_has_money_get_hist(api)) {
		return nil, notProvided("money_get_hist")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_money_get_hist(api, str(xuid), C.int32_t(timediff), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// MoneyClearHist calls the money_clear_hist slot.
func (RawAPI) MoneyClearHist(difftime int32) error {
	if api == nil || !bool(C.piergo_has_money_clear_hist(api)) {
		return notProvided("money_clear_hist")
	}
	C.piergo_call_money_clear_hist(api, C.int32_t(difftime))
	return nil
}

// MoneyRanking calls the money_ranking slot.
func (RawAPI) MoneyRanking(num uint16) ([]string, error) {
	if api == nil || !bool(C.piergo_has_money_ranking(api)) {
		return nil, notProvided("money_ranking")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_money_ranking(api, C.uint16_t(num), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// PlayerGetCarriedItem calls the player_get_carried_item slot.
//
// Player: equipment, cooldown, network (dedicated fns)
func (RawAPI) PlayerGetCarriedItem(sel PlayerSel) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_carried_item(api)) {
		return nil, false, notProvided("player_get_carried_item")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_get_carried_item(api, sel.c(), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// PlayerGetItem calls the player_get_item slot.
func (RawAPI) PlayerGetItem(sel PlayerSel, slot int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_item(api)) {
		return nil, false, notProvided("player_get_item")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_get_item(api, sel.c(), C.int32_t(slot), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// PlayerSetItem calls the player_set_item slot.
func (RawAPI) PlayerSetItem(sel PlayerSel, slot int32, itemSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_set_item(api)) {
		return false, notProvided("player_set_item")
	}
	r := C.piergo_call_player_set_item(api, sel.c(), C.int32_t(slot), str(itemSnbt))
	return bool(r), nil
}

// PlayerGetEquipment calls the player_get_equipment slot.
//
// All equipment as SNBT: [{slot, item_snbt},…] slot: 0=mainhand 1=offhand 2-5=armor
func (RawAPI) PlayerGetEquipment(sel PlayerSel) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_equipment(api)) {
		return nil, false, notProvided("player_get_equipment")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_get_equipment(api, sel.c(), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// PlayerGetCooldown calls the player_get_cooldown slot.
//
// Ticks remaining for an item cooldown (-1 if not on cooldown / player offline).
func (RawAPI) PlayerGetCooldown(sel PlayerSel, itemName string) (int32, error) {
	if api == nil || !bool(C.piergo_has_player_get_cooldown(api)) {
		return 0, notProvided("player_get_cooldown")
	}
	r := C.piergo_call_player_get_cooldown(api, sel.c(), str(itemName))
	return int32(r), nil
}

// PlayerStartCooldown calls the player_start_cooldown slot.
func (RawAPI) PlayerStartCooldown(sel PlayerSel, itemName string, ticks int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_start_cooldown(api)) {
		return false, notProvided("player_start_cooldown")
	}
	r := C.piergo_call_player_start_cooldown(api, sel.c(), str(itemName), C.int32_t(ticks))
	return bool(r), nil
}

// PlayerGetNetworkStatus calls the player_get_network_status slot.
func (RawAPI) PlayerGetNetworkStatus(sel PlayerSel) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_player_get_network_status(api)) {
		return nil, false, notProvided("player_get_network_status")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_player_get_network_status(api, sel.c(), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorGetVehicle calls the actor_get_vehicle slot.
//
// Actor: relationships, equipment, effects, geometry (dedicated fns)
func (RawAPI) ActorGetVehicle(id ActorID) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_vehicle(api)) {
		return 0, false, notProvided("actor_get_vehicle")
	}
	var o0 C.PierActorId
	r := C.piergo_call_actor_get_vehicle(api, C.PierActorId(id), &o0)
	return ActorID(o0), bool(r), nil
}

// ActorGetFirstPassenger calls the actor_get_first_passenger slot.
func (RawAPI) ActorGetFirstPassenger(id ActorID) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_first_passenger(api)) {
		return 0, false, notProvided("actor_get_first_passenger")
	}
	var o0 C.PierActorId
	r := C.piergo_call_actor_get_first_passenger(api, C.PierActorId(id), &o0)
	return ActorID(o0), bool(r), nil
}

// ActorGetOwner calls the actor_get_owner slot.
func (RawAPI) ActorGetOwner(id ActorID) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_owner(api)) {
		return 0, false, notProvided("actor_get_owner")
	}
	var o0 C.PierActorId
	r := C.piergo_call_actor_get_owner(api, C.PierActorId(id), &o0)
	return ActorID(o0), bool(r), nil
}

// ActorGetTarget calls the actor_get_target slot.
func (RawAPI) ActorGetTarget(id ActorID) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_target(api)) {
		return 0, false, notProvided("actor_get_target")
	}
	var o0 C.PierActorId
	r := C.piergo_call_actor_get_target(api, C.PierActorId(id), &o0)
	return ActorID(o0), bool(r), nil
}

// ActorGetEquippedItem calls the actor_get_equipped_item slot.
//
// slot: 0=mainhand 1=offhand 2=helmet 3=chestplate 4=leggings 5=boots
func (RawAPI) ActorGetEquippedItem(id ActorID, slot int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_equipped_item(api)) {
		return nil, false, notProvided("actor_get_equipped_item")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_get_equipped_item(api, C.PierActorId(id), C.int32_t(slot), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorSetEquippedItem calls the actor_set_equipped_item slot.
func (RawAPI) ActorSetEquippedItem(id ActorID, slot int32, itemSnbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_actor_set_equipped_item(api)) {
		return false, notProvided("actor_set_equipped_item")
	}
	r := C.piergo_call_actor_set_equipped_item(api, C.PierActorId(id), C.int32_t(slot), str(itemSnbt))
	return bool(r), nil
}

// ActorGetEffects calls the actor_get_effects slot.
//
// SNBT [{id, ticks, amplifier, visible},…]
func (RawAPI) ActorGetEffects(id ActorID) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_effects(api)) {
		return nil, false, notProvided("actor_get_effects")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_get_effects(api, C.PierActorId(id), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorGetStatusFlag calls the actor_get_status_flag slot.
//
// flag_index: ActorFlags enum value (0-based).
func (RawAPI) ActorGetStatusFlag(id ActorID, flagIndex int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_status_flag(api)) {
		return false, notProvided("actor_get_status_flag")
	}
	r := C.piergo_call_actor_get_status_flag(api, C.PierActorId(id), C.int32_t(flagIndex))
	return bool(r), nil
}

// ActorSetStatusFlag calls the actor_set_status_flag slot.
func (RawAPI) ActorSetStatusFlag(id ActorID, flagIndex int32, value bool) (bool, error) {
	if api == nil || !bool(C.piergo_has_actor_set_status_flag(api)) {
		return false, notProvided("actor_set_status_flag")
	}
	r := C.piergo_call_actor_set_status_flag(api, C.PierActorId(id), C.int32_t(flagIndex), C.bool(value))
	return bool(r), nil
}

// ActorTraceRay calls the actor_trace_ray slot.
//
// SNBT {type:"entity"|"block"|"none", pos:[x,y,z], entity_id?, block_name?}
func (RawAPI) ActorTraceRay(id ActorID, maxDist float32, includeActors bool, includeBlocks bool) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_trace_ray(api)) {
		return nil, false, notProvided("actor_trace_ray")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_trace_ray(api, C.PierActorId(id), C.float(maxDist), C.bool(includeActors), C.bool(includeBlocks), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorDistanceTo calls the actor_distance_to slot.
func (RawAPI) ActorDistanceTo(id ActorID, other ActorID) (float64, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_distance_to(api)) {
		return 0, false, notProvided("actor_distance_to")
	}
	var o0 C.double
	r := C.piergo_call_actor_distance_to(api, C.PierActorId(id), C.PierActorId(other), &o0)
	return float64(o0), bool(r), nil
}

// ActorGetAabb calls the actor_get_aabb slot.
//
// SNBT {min:[x,y,z], max:[x,y,z]}
func (RawAPI) ActorGetAabb(id ActorID) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_get_aabb(api)) {
		return nil, false, notProvided("actor_get_aabb")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_actor_get_aabb(api, C.PierActorId(id), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ActorClone calls the actor_clone slot.
func (RawAPI) ActorClone(id ActorID, dim int32, x float64, y float64, z float64) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_actor_clone(api)) {
		return 0, false, notProvided("actor_clone")
	}
	var o0 C.PierActorId
	r := C.piergo_call_actor_clone(api, C.PierActorId(id), C.int32_t(dim), C.double(x), C.double(y), C.double(z), &o0)
	return ActorID(o0), bool(r), nil
}

// BlockGetState calls the block_get_state slot.
//
// Block: state get/set, collision shape (dedicated fns)
func (RawAPI) BlockGetState(dim int32, x int32, y int32, z int32, stateName string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_block_get_state(api)) {
		return nil, false, notProvided("block_get_state")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_block_get_state(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(stateName), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// BlockSetState calls the block_set_state slot.
func (RawAPI) BlockSetState(dim int32, x int32, y int32, z int32, stateName string, value string) (bool, error) {
	if api == nil || !bool(C.piergo_has_block_set_state(api)) {
		return false, notProvided("block_set_state")
	}
	r := C.piergo_call_block_set_state(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(stateName), str(value))
	return bool(r), nil
}

// BlockGetCollisionShape calls the block_get_collision_shape slot.
func (RawAPI) BlockGetCollisionShape(dim int32, x int32, y int32, z int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_block_get_collision_shape(api)) {
		return nil, false, notProvided("block_get_collision_shape")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_block_get_collision_shape(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ItemGetEnchants calls the item_get_enchants slot.
//
// SNBT [{id, level},…]
func (RawAPI) ItemGetEnchants(itemSnbt string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_item_get_enchants(api)) {
		return nil, false, notProvided("item_get_enchants")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_item_get_enchants(api, str(itemSnbt), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ItemSetEnchants calls the item_set_enchants slot.
//
// enchants_snbt = [{id, level},…]; out = new item SNBT. NULL on every
// current host: writing enchantments is not implemented, and
// item_get_enchants is the read side.
func (RawAPI) ItemSetEnchants(itemSnbt string, enchantsSnbt string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_item_set_enchants(api)) {
		return nil, false, notProvided("item_set_enchants")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_item_set_enchants(api, str(itemSnbt), str(enchantsSnbt), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ItemMatches calls the item_matches slot.
func (RawAPI) ItemMatches(a string, b string) (bool, error) {
	if api == nil || !bool(C.piergo_has_item_matches(api)) {
		return false, notProvided("item_matches")
	}
	r := C.piergo_call_item_matches(api, str(a), str(b))
	return bool(r), nil
}

// ItemGetUserData calls the item_get_user_data slot.
func (RawAPI) ItemGetUserData(itemSnbt string) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_item_get_user_data(api)) {
		return nil, false, notProvided("item_get_user_data")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_item_get_user_data(api, str(itemSnbt), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// LevelGetBiome calls the level_get_biome slot.
//
// Level: biome, spawn, save, weather, path, sleep (dedicated fns)
func (RawAPI) LevelGetBiome(dim int32, x int32, y int32, z int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_level_get_biome(api)) {
		return nil, false, notProvided("level_get_biome")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_level_get_biome(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// LevelGetDefaultSpawn calls the level_get_default_spawn slot.
func (RawAPI) LevelGetDefaultSpawn() (int32, int32, int32, bool, error) {
	if api == nil || !bool(C.piergo_has_level_get_default_spawn(api)) {
		return 0, 0, 0, false, notProvided("level_get_default_spawn")
	}
	var o0 C.int32_t
	var o1 C.int32_t
	var o2 C.int32_t
	r := C.piergo_call_level_get_default_spawn(api, &o0, &o1, &o2)
	return int32(o0), int32(o1), int32(o2), bool(r), nil
}

// LevelSetDefaultSpawn calls the level_set_default_spawn slot.
func (RawAPI) LevelSetDefaultSpawn(x int32, y int32, z int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_level_set_default_spawn(api)) {
		return false, notProvided("level_set_default_spawn")
	}
	r := C.piergo_call_level_set_default_spawn(api, C.int32_t(x), C.int32_t(y), C.int32_t(z))
	return bool(r), nil
}

// LevelSave calls the level_save slot.
func (RawAPI) LevelSave() (bool, error) {
	if api == nil || !bool(C.piergo_has_level_save(api)) {
		return false, notProvided("level_save")
	}
	r := C.piergo_call_level_save(api)
	return bool(r), nil
}

// LevelGetSleepStatus calls the level_get_sleep_status slot.
//
// SNBT {sleeping, total_players, active_sleeping}
func (RawAPI) LevelGetSleepStatus() ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_level_get_sleep_status(api)) {
		return nil, false, notProvided("level_get_sleep_status")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_level_get_sleep_status(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// LevelUpdateWeather calls the level_update_weather slot.
func (RawAPI) LevelUpdateWeather(rainLevel float32, rainTime int32, lightningLevel float32, lightningTime int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_level_update_weather(api)) {
		return false, notProvided("level_update_weather")
	}
	r := C.piergo_call_level_update_weather(api, C.float(rainLevel), C.int32_t(rainTime), C.float(lightningLevel), C.int32_t(lightningTime))
	return bool(r), nil
}

// LevelFindPath calls the level_find_path slot.
//
// SNBT {nodes:[{x,y,z},…], reached:1b/0b}. NULL on every current host:
// pathfinding is not implemented.
func (RawAPI) LevelFindPath(id ActorID, x int32, y int32, z int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_level_find_path(api)) {
		return nil, false, notProvided("level_find_path")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_level_find_path(api, C.PierActorId(id), C.int32_t(x), C.int32_t(y), C.int32_t(z), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// PacketHookUnregister calls the packet_hook_unregister slot.
//
// Unregister. Safe to call from inside the callback.
func (RawAPI) PacketHookUnregister(handleArg PacketHookHandle) (bool, error) {
	if api == nil || !bool(C.piergo_has_packet_hook_unregister(api)) {
		return false, notProvided("packet_hook_unregister")
	}
	r := C.piergo_call_packet_hook_unregister(api, self, C.PierPacketHookHandle(handleArg.p))
	return bool(r), nil
}

// PacketConnHookUnregister calls the packet_conn_hook_unregister slot.
//
// Unregister. Safe to call from inside the callback.
func (RawAPI) PacketConnHookUnregister(handleArg PacketHookHandle) (bool, error) {
	if api == nil || !bool(C.piergo_has_packet_conn_hook_unregister(api)) {
		return false, notProvided("packet_conn_hook_unregister")
	}
	r := C.piergo_call_packet_conn_hook_unregister(api, self, C.PierPacketHookHandle(handleArg.p))
	return bool(r), nil
}

// ClientGetLocalPlayer calls the client_get_local_player slot.
//
// Local player's name via ll::service::getClientInstance()->getLocalPlayer().
// sink receives the name, or the call returns false if not in a level.
func (RawAPI) ClientGetLocalPlayer() ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_client_get_local_player(api)) {
		return nil, false, notProvided("client_get_local_player")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_client_get_local_player(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ClientIsInLevel calls the client_is_in_level slot.
//
// True when the client is inside a level (a world is loaded).
func (RawAPI) ClientIsInLevel() (bool, error) {
	if api == nil || !bool(C.piergo_has_client_is_in_level(api)) {
		return false, notProvided("client_is_in_level")
	}
	r := C.piergo_call_client_is_in_level(api)
	return bool(r), nil
}

// ClientGetScreenName calls the client_get_screen_name slot.
//
// Current screen / UI name (e.g. "hud_screen", "pause_screen"). NULL on
// every current host, client builds included: the engine exposes no
// stable accessor for it.
func (RawAPI) ClientGetScreenName() ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_client_get_screen_name(api)) {
		return nil, false, notProvided("client_get_screen_name")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_client_get_screen_name(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// ClientUnregisterKey calls the client_unregister_key slot.
//
// Unregister a key binding: this mod's handler stops firing and the handle
// is freed. The ll::input::KeyHandle itself is not destroyed, since the key
// registry keeps one key per name and offers no removal; registering the
// same name again reuses that key.
func (RawAPI) ClientUnregisterKey(handleArg KeyHandle) (bool, error) {
	if api == nil || !bool(C.piergo_has_client_unregister_key(api)) {
		return false, notProvided("client_unregister_key")
	}
	r := C.piergo_call_client_unregister_key(api, C.PierKeyHandle(handleArg.p))
	return bool(r), nil
}

// ClientGetKeyCodes calls the client_get_key_codes slot.
//
// Currently assigned key codes (may differ from defaults if remapped).
// sink receives a JSON-style array string "[1,2,3]".
func (RawAPI) ClientGetKeyCodes(handleArg KeyHandle) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_client_get_key_codes(api)) {
		return nil, false, notProvided("client_get_key_codes")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_client_get_key_codes(api, C.PierKeyHandle(handleArg.p), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// MdIsAvailable calls the md_is_available slot.
//
// Whether this host can register custom dimensions. NULL when pier-dimensions
// was not built in. Filled in, it answers from a probe of the engine's dimension
// definition table, so it can be false on an engine whose layout this build does
// not match; the answer is cached after the first call that can make it.
func (RawAPI) MdIsAvailable() (bool, error) {
	if api == nil || !bool(C.piergo_has_md_is_available(api)) {
		return false, notProvided("md_is_available")
	}
	r := C.piergo_call_md_is_available(api)
	return bool(r), nil
}

// MdSetDimensionRule calls the md_set_dimension_rule slot.
//
// Per-dimension rules, consulted by the loader's own hooks.
func (RawAPI) MdSetDimensionRule(dimension int32, rule int32, allow bool) error {
	if api == nil || !bool(C.piergo_has_md_set_dimension_rule(api)) {
		return notProvided("md_set_dimension_rule")
	}
	C.piergo_call_md_set_dimension_rule(api, C.int32_t(dimension), C.int32_t(rule), C.bool(allow))
	return nil
}

// MdGetDimensionRule calls the md_get_dimension_rule slot.
//
// Read back a rule. `outAllow` is only written when the dimension has an
// explicit entry for that rule; returns false otherwise. A rule number this
// host does not know is answered false as well, and md_set_dimension_rule
// ignores one, so a binding newer than the host cannot tell "not set" from
// "not supported" here.
func (RawAPI) MdGetDimensionRule(dimension int32, rule int32) (bool, bool, error) {
	if api == nil || !bool(C.piergo_has_md_get_dimension_rule(api)) {
		return false, false, notProvided("md_get_dimension_rule")
	}
	var o0 C.bool
	r := C.piergo_call_md_get_dimension_rule(api, C.int32_t(dimension), C.int32_t(rule), &o0)
	return bool(o0), bool(r), nil
}

// MdClearDimensionRules calls the md_clear_dimension_rules slot.
//
// Drop every rule for a dimension (used when a world is deleted).
func (RawAPI) MdClearDimensionRules(dimension int32) error {
	if api == nil || !bool(C.piergo_has_md_clear_dimension_rules(api)) {
		return notProvided("md_clear_dimension_rules")
	}
	C.piergo_call_md_clear_dimension_rules(api, C.int32_t(dimension))
	return nil
}

// MdGetDimensionId calls the md_get_dimension_id slot.
//
// Resolve a dimension name to its id. Returns -1 if not found.
func (RawAPI) MdGetDimensionId(name string) (int32, error) {
	if api == nil || !bool(C.piergo_has_md_get_dimension_id(api)) {
		return 0, notProvided("md_get_dimension_id")
	}
	r := C.piergo_call_md_get_dimension_id(api, str(name))
	return int32(r), nil
}

// ScheduleCancel calls the schedule_cancel slot.
//
// Drop a task scheduled by this mod if it has not run yet. Returns true
// if a pending task was actually dropped. Safe to call from any thread
// and from inside another task. Cancelling leaks `user` for the same
// reason as above, so prefer letting short tasks run.
func (RawAPI) ScheduleCancel(taskId uint64) (bool, error) {
	if api == nil || !bool(C.piergo_has_schedule_cancel(api)) {
		return false, notProvided("schedule_cancel")
	}
	r := C.piergo_call_schedule_cancel(api, self, C.uint64_t(taskId))
	return bool(r), nil
}

// SchedulePendingCount calls the schedule_pending_count slot.
//
// Number of tasks this mod still has pending. Intended for a mod to
// assert it has drained its own work in on_disable / on_unload, which is
// a precondition for being marked "reload_safe" in its manifest.
func (RawAPI) SchedulePendingCount() (uint32, error) {
	if api == nil || !bool(C.piergo_has_schedule_pending_count(api)) {
		return 0, notProvided("schedule_pending_count")
	}
	r := C.piergo_call_schedule_pending_count(api, self)
	return uint32(r), nil
}

// ContainerRefresh calls the container_refresh slot.
//
// Resend a player-owned container (which 0..3) to its owner. Returns
// false for block containers (which == 4) — a chest has no single owner
// to resend to; its viewers are refreshed by the engine's own container
// transaction path.
func (RawAPI) ContainerRefresh(ref ContainerRef) (bool, error) {
	if api == nil || !bool(C.piergo_has_container_refresh(api)) {
		return false, notProvided("container_refresh")
	}
	r := C.piergo_call_container_refresh(api, ref.c())
	return bool(r), nil
}

// PlayerSendTitle calls the player_send_title slot.
//
// Titles
// `PACT_SET_TITLE` (player_action opcode 6) reaches the client by running
// the console command `title "<name>" title <text>`. Three things are
// wrong with that and none of them are theoretical:
// - the text is pasted into a command line unquoted, so a plot named
// `He said "hi"` truncates the command;
// - `title`'s text parameter is a `message`, which expands selectors —
// a plot named `@e` is a command injection, not a name;
// - `/title` has no way to set fade/stay for the same call, so timing is
// whatever the client last stored.
// This slot builds a real SetTitlePacket instead. No wire format crosses
// the FFI (the packet is constructed field-by-field on this side), so it
// survives protocol bumps the way `spawn_particle_for` does.
func (RawAPI) PlayerSendTitle(sel PlayerSel, typeArg int32, text string, fadeInTicks int32, stayTicks int32, fadeOutTicks int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_player_send_title(api)) {
		return false, notProvided("player_send_title")
	}
	r := C.piergo_call_player_send_title(api, sel.c(), C.int32_t(typeArg), str(text), C.int32_t(fadeInTicks), C.int32_t(stayTicks), C.int32_t(fadeOutTicks))
	return bool(r), nil
}

// BusUnsubscribe calls the bus_unsubscribe slot.
//
// Drop one of this mod's subscriptions. Scoped to the caller — a mod
// cannot unsubscribe another mod. Returns true if one was removed.
// Safe to call from inside a callback (including one's own).
func (RawAPI) BusUnsubscribe(subId uint64) (bool, error) {
	if api == nil || !bool(C.piergo_has_bus_unsubscribe(api)) {
		return false, notProvided("bus_unsubscribe")
	}
	r := C.piergo_call_bus_unsubscribe(api, self, C.uint64_t(subId))
	return bool(r), nil
}

// BusPublish calls the bus_publish slot.
//
// Deliver `payload` to every *other* mod subscribed to `topic`. Returns
// how many subscribers actually ran (0 is normal — nobody is listening).
// Return values from subscribers are ignored.
func (RawAPI) BusPublish(topic string, payload string) (uint32, error) {
	if api == nil || !bool(C.piergo_has_bus_publish(api)) {
		return 0, notProvided("bus_publish")
	}
	r := C.piergo_call_bus_publish(api, self, str(topic), str(payload))
	return uint32(r), nil
}

// BusPublishVetoable calls the bus_publish_vetoable slot.
//
// As above, but collects the veto bit: returns true when any
// subscriber returned true. Every subscriber still runs — no
// short-circuit — so observers see a consistent stream whether or not an
// earlier one refused. `out_delivered` may be NULL.
func (RawAPI) BusPublishVetoable(topic string, payload string) (uint32, bool, error) {
	if api == nil || !bool(C.piergo_has_bus_publish_vetoable(api)) {
		return 0, false, notProvided("bus_publish_vetoable")
	}
	var o0 C.uint32_t
	r := C.piergo_call_bus_publish_vetoable(api, self, str(topic), str(payload), &o0)
	return uint32(o0), bool(r), nil
}

// BusSubscriberCount calls the bus_subscriber_count slot.
//
// How many subscribers a topic has right now, across all mods. Intended
// for skipping the cost of building a payload nobody will read.
func (RawAPI) BusSubscriberCount(topic string) (uint32, error) {
	if api == nil || !bool(C.piergo_has_bus_subscriber_count(api)) {
		return 0, notProvided("bus_subscriber_count")
	}
	r := C.piergo_call_bus_subscriber_count(api, str(topic))
	return uint32(r), nil
}

// MdSetPlotMerges calls the md_set_plot_merges slot.
//
// Replace a dimension's merge markers wholesale. `entries` is `count`
// triples `(x, z, mask)`, i.e. `count * 3` int32s; `mask` is a bitset of
// 1=north, 2=east, 4=south, 8=west matching the plugin's `merged[]`
// indices. Only plots that actually carry a marker need to be sent.
func (RawAPI) MdSetPlotMerges(dimension int32, entries []int32) error {
	if api == nil || !bool(C.piergo_has_md_set_plot_merges(api)) {
		return notProvided("md_set_plot_merges")
	}
	C.piergo_call_md_set_plot_merges(api, C.int32_t(dimension), int32sPtr(entries), C.int32_t(len(entries)))
	return nil
}

// ServiceUnregister calls the service_unregister slot.
//
// Drop one of this mod's registrations. Scoped to the caller — a mod
// cannot unregister another mod's service.
func (RawAPI) ServiceUnregister(regId uint64) (bool, error) {
	if api == nil || !bool(C.piergo_has_service_unregister(api)) {
		return false, notProvided("service_unregister")
	}
	r := C.piergo_call_service_unregister(api, self, C.uint64_t(regId))
	return bool(r), nil
}

// ServiceCall calls the service_call slot.
//
// Call `name` with `request`; the provider's answer arrives through
// `reply`. Returns one of PIER_SERVICE_*. A mod cannot call its own
// service (it has a direct function call, and self-calls are the least
// legible loop shape).
func (RawAPI) ServiceCall(name string, request string) ([]string, int32, error) {
	if api == nil || !bool(C.piergo_has_service_call(api)) {
		return nil, 0, notProvided("service_call")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_service_call(api, self, str(name), str(request), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, int32(r), nil
}

// ServiceList calls the service_list slot.
//
// Every registered service as a JSON array of `{"name":…,"mod":…}`.
// For diagnostics and for a caller deciding whether to build a request
// nobody can answer.
func (RawAPI) ServiceList() ([]string, error) {
	if api == nil || !bool(C.piergo_has_service_list(api)) {
		return nil, notProvided("service_list")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_service_list(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// EditSetBlockNbt calls the edit_set_block_nbt slot.
//
// Write a block from serialized NBT ({name,states,version}, i.e. the
// shape get_block produces).
func (RawAPI) EditSetBlockNbt(dim int32, x int32, y int32, z int32, snbt string, updateFlags int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_edit_set_block_nbt(api)) {
		return false, notProvided("edit_set_block_nbt")
	}
	r := C.piergo_call_edit_set_block_nbt(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(snbt), C.int32_t(updateFlags))
	return bool(r), nil
}

// EditSetBlockStates calls the edit_set_block_states slot.
//
// Write a block from a name + optional partial states. An empty
// states_snbt means all-default states; the version is taken from the
// default state on the loader side — the caller must not supply one.
func (RawAPI) EditSetBlockStates(dim int32, x int32, y int32, z int32, name string, statesSnbt string, updateFlags int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_edit_set_block_states(api)) {
		return false, notProvided("edit_set_block_states")
	}
	r := C.piergo_call_edit_set_block_states(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(name), str(statesSnbt), C.int32_t(updateFlags))
	return bool(r), nil
}

// EditSetBlockEntity calls the edit_set_block_entity slot.
//
// Write a block entity's NBT back (BlockActor::load). The cell must
// already hold the matching block.
func (RawAPI) EditSetBlockEntity(dim int32, x int32, y int32, z int32, snbt string) (bool, error) {
	if api == nil || !bool(C.piergo_has_edit_set_block_entity(api)) {
		return false, notProvided("edit_set_block_entity")
	}
	r := C.piergo_call_edit_set_block_entity(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(snbt))
	return bool(r), nil
}

// EditSpawnEntityNbt calls the edit_spawn_entity_nbt slot.
//
// Spawn an entity from full NBT (the inverse of actor_snapshot). When
// use_pos is true, (x,y,z) overrides the Pos tag; the UniqueID is
// reassigned by the engine and returned via out.
// NULL on every current host: the engine helper that gives a loaded
// actor a fresh UniqueID is inlined, and reusing the snapshot's own id
// makes the engine treat two actors as one.
func (RawAPI) EditSpawnEntityNbt(dim int32, snbt string, usePos bool, x float64, y float64, z float64) (ActorID, bool, error) {
	if api == nil || !bool(C.piergo_has_edit_spawn_entity_nbt(api)) {
		return 0, false, notProvided("edit_spawn_entity_nbt")
	}
	var o0 C.PierActorId
	r := C.piergo_call_edit_spawn_entity_nbt(api, C.int32_t(dim), str(snbt), C.bool(usePos), C.double(x), C.double(y), C.double(z), &o0)
	return ActorID(o0), bool(r), nil
}

// EditTraceRay calls the edit_trace_ray slot.
//
// Ray trace yielding the BLOCK coordinate and hit face:
// {type, block:[x,y,z], facing, pos:[x,y,z], entity}.
func (RawAPI) EditTraceRay(id ActorID, maxDist float32, includeActors bool, includeBlocks bool) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_edit_trace_ray(api)) {
		return nil, false, notProvided("edit_trace_ray")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_edit_trace_ray(api, C.PierActorId(id), C.float(maxDist), C.bool(includeActors), C.bool(includeBlocks), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// LaneUnpublish calls the lane_unpublish slot.
//
// Withdraw a lane owned by this mod. Calls release for every outstanding
// lease and clears the liveness flag, so a consumer's next check sees the
// lane gone instead of jumping through a dead pointer.
func (RawAPI) LaneUnpublish(pubId uint64) (bool, error) {
	if api == nil || !bool(C.piergo_has_lane_unpublish(api)) {
		return false, notProvided("lane_unpublish")
	}
	r := C.piergo_call_lane_unpublish(api, self, C.uint64_t(pubId))
	return bool(r), nil
}

// LaneRelease calls the lane_release slot.
//
// Return a lease. Only a lease held by this mod. Returns false when the
// provider is already gone, since the loader has called release for it by
// then and calling again would be a double free.
func (RawAPI) LaneRelease(lease uint64) (bool, error) {
	if api == nil || !bool(C.piergo_has_lane_release(api)) {
		return false, notProvided("lane_release")
	}
	r := C.piergo_call_lane_release(api, self, C.uint64_t(lease))
	return bool(r), nil
}

// LaneList calls the lane_list slot.
//
// Every lane, as a JSON array:
// [{"name":…,"mod":…,"fingerprint":"0x…","protocol":1,"leases":N,"alive":true}]
func (RawAPI) LaneList() ([]string, error) {
	if api == nil || !bool(C.piergo_has_lane_list(api)) {
		return nil, notProvided("lane_list")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_lane_list(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// MdListDimensions calls the md_list_dimensions slot.
//
// List every registered custom dimension as a JSON array:
// [{"name":"plot_world","dim":1000,"snbt":"{…}"}].
func (RawAPI) MdListDimensions() ([]string, error) {
	if api == nil || !bool(C.piergo_has_md_list_dimensions(api)) {
		return nil, notProvided("md_list_dimensions")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_md_list_dimensions(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// LevelDeleteChunkKeys calls the level_delete_chunk_keys slot.
//
// Delete every save-file key belonging to one chunk, so the engine
// regenerates it from the generator on next load.
func (RawAPI) LevelDeleteChunkKeys(dim int32, chunkX int32, chunkZ int32) (int32, error) {
	if api == nil || !bool(C.piergo_has_level_delete_chunk_keys(api)) {
		return 0, notProvided("level_delete_chunk_keys")
	}
	r := C.piergo_call_level_delete_chunk_keys(api, C.int32_t(dim), C.int32_t(chunkX), C.int32_t(chunkZ))
	return int32(r), nil
}

// LevelChunksLoaded calls the level_chunks_loaded slot.
//
// Are the chunks covering [min..max] currently loaded in memory?
func (RawAPI) LevelChunksLoaded(dim int32, minX int32, minZ int32, maxX int32, maxZ int32) (int32, error) {
	if api == nil || !bool(C.piergo_has_level_chunks_loaded(api)) {
		return 0, notProvided("level_chunks_loaded")
	}
	r := C.piergo_call_level_chunks_loaded(api, C.int32_t(dim), C.int32_t(minX), C.int32_t(minZ), C.int32_t(maxX), C.int32_t(maxZ))
	return int32(r), nil
}

// PlayerConnId calls the player_conn_id slot.
//
// This player's connection id — the same number packet interceptors see
// in the packet context.
func (RawAPI) PlayerConnId(who PlayerSel) (uint64, error) {
	if api == nil || !bool(C.piergo_has_player_conn_id(api)) {
		return 0, notProvided("player_conn_id")
	}
	r := C.piergo_call_player_conn_id(api, who.c())
	return uint64(r), nil
}

// LevelChunkKeys calls the level_chunk_keys slot.
//
// List every save-file key belonging to one chunk. One callback per key.
func (RawAPI) LevelChunkKeys(dim int32, chunkX int32, chunkZ int32) ([]string, int32, error) {
	if api == nil || !bool(C.piergo_has_level_chunk_keys(api)) {
		return nil, 0, notProvided("level_chunk_keys")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_level_chunk_keys(api, C.int32_t(dim), C.int32_t(chunkX), C.int32_t(chunkZ), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, int32(r), nil
}

// LevelDeleteKey calls the level_delete_key slot.
//
// Delete one chunk-category key, verbatim.
func (RawAPI) LevelDeleteKey(key string) (bool, error) {
	if api == nil || !bool(C.piergo_has_level_delete_key(api)) {
		return false, notProvided("level_delete_key")
	}
	r := C.piergo_call_level_delete_key(api, str(key))
	return bool(r), nil
}

// LevelSetBiome calls the level_set_biome slot.
//
// Set the biome over an area.
func (RawAPI) LevelSetBiome(dim int32, minX int32, minZ int32, maxX int32, maxZ int32, biome string) (int32, error) {
	if api == nil || !bool(C.piergo_has_level_set_biome(api)) {
		return 0, notProvided("level_set_biome")
	}
	r := C.piergo_call_level_set_biome(api, C.int32_t(dim), C.int32_t(minX), C.int32_t(minZ), C.int32_t(maxX), C.int32_t(maxZ), str(biome))
	return int32(r), nil
}

// GetExtraBlock calls the get_extra_block slot.
//
// Read the liquid layer. The sink receives a block name such as
// "minecraft:water"; an empty layer gives air.
func (RawAPI) GetExtraBlock(dim int32, x int32, y int32, z int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_get_extra_block(api)) {
		return nil, false, notProvided("get_extra_block")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_get_extra_block(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}

// SetExtraBlock calls the set_extra_block slot.
//
// Write the liquid layer. block_spec takes a bare block name or full SNBT;
// write "minecraft:air" to clear it. update_flags is as in
// edit_set_block_nbt: bit 1 notifies neighbours, bit 2 syncs the client.
func (RawAPI) SetExtraBlock(dim int32, x int32, y int32, z int32, blockSpec string, updateFlags int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_set_extra_block(api)) {
		return false, notProvided("set_extra_block")
	}
	r := C.piergo_call_set_extra_block(api, C.int32_t(dim), C.int32_t(x), C.int32_t(y), C.int32_t(z), str(blockSpec), C.int32_t(updateFlags))
	return bool(r), nil
}

// GetTps calls the get_tps slot.
//
// Ticks per second over the last `window_seconds` (1..60, clipped) of wall
// clock: the number of Level::tick calls that really ran divided by elapsed
// time. Stays correct under the tick warp (reads above 20), the tick freeze
// (reads 0) and lag (reads below 20). Returns -1.0 before the first frame
// has been sampled. Server thread only.
func (RawAPI) GetTps(windowSeconds int32) (float64, error) {
	if api == nil || !bool(C.piergo_has_get_tps(api)) {
		return 0, notProvided("get_tps")
	}
	r := C.piergo_call_get_tps(api, C.int32_t(windowSeconds))
	return float64(r), nil
}

// GetMspt calls the get_mspt slot.
//
// Milliseconds spent inside Level::tick per tick, averaged over the last
// `window_seconds` (1..60, clipped). This is the time the server computes,
// excluding the idle sleep between frames; a healthy server reads a few
// milliseconds and only approaches 50 when saturated. Returns -1.0 when no
// tick ran in the window. Server thread only.
func (RawAPI) GetMspt(windowSeconds int32) (float64, error) {
	if api == nil || !bool(C.piergo_has_get_mspt(api)) {
		return 0, notProvided("get_mspt")
	}
	r := C.piergo_call_get_mspt(api, C.int32_t(windowSeconds))
	return float64(r), nil
}

// EditFillRegion calls the edit_fill_region slot.
//
// Fills a box with one block. block_spec is a bare name such as
// "minecraft:stone" or full SNBT; it is resolved once for the whole box.
// update_flags is as in edit_set_block_nbt: bit 1 notifies neighbours, bit
// 2 syncs the client; 0 is the fastest and leaves the client to catch up on
// the next chunk send. Returns the number of cells written, or -1 if the
// dimension is not ready, the spec does not resolve, or the box exceeds
// 2^24 cells. Server thread only.
func (RawAPI) EditFillRegion(dimension int32, x1 int32, y1 int32, z1 int32, x2 int32, y2 int32, z2 int32, blockSpec string, updateFlags int32) (int64, error) {
	if api == nil || !bool(C.piergo_has_edit_fill_region(api)) {
		return 0, notProvided("edit_fill_region")
	}
	r := C.piergo_call_edit_fill_region(api, C.int32_t(dimension), C.int32_t(x1), C.int32_t(y1), C.int32_t(z1), C.int32_t(x2), C.int32_t(y2), C.int32_t(z2), str(blockSpec), C.int32_t(updateFlags))
	return int64(r), nil
}

// MdAddDimension calls the md_add_dimension slot.
//
// Add a custom dimension with a native terrain from one declarative spec.
func (RawAPI) MdAddDimension(name string, specSnbt string) (int32, error) {
	if api == nil || !bool(C.piergo_has_md_add_dimension(api)) {
		return 0, notProvided("md_add_dimension")
	}
	r := C.piergo_call_md_add_dimension(api, str(name), str(specSnbt))
	return int32(r), nil
}

// MdAddDimensionPack calls the md_add_dimension_pack slot.
//
// Add a custom dimension whose terrain is a terrain pack: a directory with a
// config file and a binary built by tools/pier-pack. `config_path` names the
// config relative to the server root, forward slashes, no ".." and not
// absolute; the binary is named inside the config relative to it.
func (RawAPI) MdAddDimensionPack(name string, configPath string, specSnbt string) (int32, error) {
	if api == nil || !bool(C.piergo_has_md_add_dimension_pack(api)) {
		return 0, notProvided("md_add_dimension_pack")
	}
	r := C.piergo_call_md_add_dimension_pack(api, str(name), str(configPath), str(specSnbt))
	return int32(r), nil
}

// MdPackInspect calls the md_pack_inspect slot.
//
// What a pack asks for, without registering anything: the sink receives one
// JSON document, the same shape `pier-pack inspect` prints:
// {"ok":true,"kind":"template","pack":"...","sha256":"...","name":"...",
// "biome":"...","height":{"min":-512,"max":320,"fixed":false},
// "params":[{"name":"plot_size","kind":"free","default":64,"min":4,
// "max":512,"step":1},
// {"name":"wall_style","kind":"choice","default":0,"choices":[0,1]},
// {"name":"plot_depth","kind":"derived"},
// {"name":"size","kind":"fixed","value":256}],
// "roles":[{"name":"floor","default":"minecraft:grass_block"}],
// "zones":["interior","border","road"],
// "constraints":["..."], "shapes":23, "picks":1,
// "voxels":[{"size":[5,4,3],"palette":5}], "confine":true}
// A mod builds its form from "params": free is a slider, choice a list, fixed a
// read-only value, derived is not shown. On a refusal the sink receives
// {"ok":false,"status":<code>,"problems":["..."]} and the code is returned.
// Returns 0 or a PIER_PACK_* code. Server thread only.
func (RawAPI) MdPackInspect(configPath string) ([]string, int32, error) {
	if api == nil || !bool(C.piergo_has_md_pack_inspect(api)) {
		return nil, 0, notProvided("md_pack_inspect")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_md_pack_inspect(api, str(configPath), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, int32(r), nil
}

// MdRetireDimension calls the md_retire_dimension slot.
//
// Retire a custom dimension: drop it from dimension_config.json, from the host's
// own tables and from the dimension factory, so nothing registers it on the next
// boot and it stops appearing in md_list_dimensions.
func (RawAPI) MdRetireDimension(name string) (bool, error) {
	if api == nil || !bool(C.piergo_has_md_retire_dimension(api)) {
		return false, notProvided("md_retire_dimension")
	}
	r := C.piergo_call_md_retire_dimension(api, str(name))
	return bool(r), nil
}

// ServiceCaller calls the service_caller slot.
//
// Who is calling the service callback that is running right now.
func (RawAPI) ServiceCaller() ([]string, error) {
	if api == nil || !bool(C.piergo_has_service_caller(api)) {
		return nil, notProvided("service_caller")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	C.piergo_call_service_caller(api, handle(uintptr(h)), C.piergo_str_sink())
	return col.items, nil
}

// MdSetDimensionCells calls the md_set_dimension_cells slot.
//
// Give a generated dimension the cell geometry its confinement rules use.
func (RawAPI) MdSetDimensionCells(dimId int32, cell int32, gap int32) (bool, error) {
	if api == nil || !bool(C.piergo_has_md_set_dimension_cells(api)) {
		return false, notProvided("md_set_dimension_cells")
	}
	r := C.piergo_call_md_set_dimension_cells(api, C.int32_t(dimId), C.int32_t(cell), C.int32_t(gap))
	return bool(r), nil
}

// RegistryList calls the registry_list slot.
//
// Lists one of the engine's registries through `sink`, one JSON object per entry, in
// no particular order. `kind` is a PIER_REGISTRY_* value.
func (RawAPI) RegistryList(kind int32) ([]string, bool, error) {
	if api == nil || !bool(C.piergo_has_registry_list(api)) {
		return nil, false, notProvided("registry_list")
	}
	col := &collector{}
	h := cgo.NewHandle(col)
	defer h.Delete()
	r := C.piergo_call_registry_list(api, C.int32_t(kind), handle(uintptr(h)), C.piergo_str_sink())
	return col.items, bool(r), nil
}
