/* slots_gen.h: one forwarding function and one gate per PierApi slot, for cgo.
 * Generated by tools/gen-go-slots.py from sdk/abi.h; edit the generator, not this. */
#ifndef PIERGO_SLOTS_GEN_H
#define PIERGO_SLOTS_GEN_H

#include <stddef.h>

#include "sdk/abi.h"

static inline bool piergo_has_log(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, log) + sizeof(api->log)
        && api->log != NULL;
}
static inline void piergo_call_log(const PierApi* api, PierModHandle a0, int32_t a1, PierStr a2)
{
    api->log(a0, a1, a2);
}

static inline bool piergo_has_gaming_status(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, gaming_status) + sizeof(api->gaming_status)
        && api->gaming_status != NULL;
}
static inline int32_t piergo_call_gaming_status(const PierApi* api)
{
    return api->gaming_status();
}

static inline bool piergo_has_schedule(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule) + sizeof(api->schedule)
        && api->schedule != NULL;
}
static inline void piergo_call_schedule(const PierApi* api, PierTaskCb a0, void* a1)
{
    api->schedule(a0, a1);
}

static inline bool piergo_has_schedule_after(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule_after) + sizeof(api->schedule_after)
        && api->schedule_after != NULL;
}
static inline void piergo_call_schedule_after(const PierApi* api, PierTaskCb a0, void* a1, uint64_t a2)
{
    api->schedule_after(a0, a1, a2);
}

static inline bool piergo_has_subscribe_event(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, subscribe_event) + sizeof(api->subscribe_event)
        && api->subscribe_event != NULL;
}
static inline PierListenerHandle piergo_call_subscribe_event(const PierApi* api, PierModHandle a0, PierStr a1, int32_t a2, PierEventCb a3, void* a4)
{
    return api->subscribe_event(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_unsubscribe_event(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, unsubscribe_event) + sizeof(api->unsubscribe_event)
        && api->unsubscribe_event != NULL;
}
static inline bool piergo_call_unsubscribe_event(const PierApi* api, PierModHandle a0, PierListenerHandle a1)
{
    return api->unsubscribe_event(a0, a1);
}

static inline bool piergo_has_list_events(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, list_events) + sizeof(api->list_events)
        && api->list_events != NULL;
}
static inline void piergo_call_list_events(const PierApi* api, void* a0, PierStrSink a1)
{
    api->list_events(a0, a1);
}

static inline bool piergo_has_execute_command(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, execute_command) + sizeof(api->execute_command)
        && api->execute_command != NULL;
}
static inline bool piergo_call_execute_command(const PierApi* api, PierStr a0, void* a1, PierCmdOutputSink a2)
{
    return api->execute_command(a0, a1, a2);
}

static inline bool piergo_has_register_command(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, register_command) + sizeof(api->register_command)
        && api->register_command != NULL;
}
static inline bool piergo_call_register_command(const PierApi* api, PierModHandle a0, PierStr a1, PierStr a2, int32_t a3, PierCommandCb a4, void* a5)
{
    return api->register_command(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_get_current_tick(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_current_tick) + sizeof(api->get_current_tick)
        && api->get_current_tick != NULL;
}
static inline uint64_t piergo_call_get_current_tick(const PierApi* api)
{
    return api->get_current_tick();
}

static inline bool piergo_has_get_tick_delta_time(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_tick_delta_time) + sizeof(api->get_tick_delta_time)
        && api->get_tick_delta_time != NULL;
}
static inline double piergo_call_get_tick_delta_time(const PierApi* api)
{
    return api->get_tick_delta_time();
}

static inline bool piergo_has_get_player_count(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_player_count) + sizeof(api->get_player_count)
        && api->get_player_count != NULL;
}
static inline int32_t piergo_call_get_player_count(const PierApi* api)
{
    return api->get_player_count();
}

static inline bool piergo_has_get_sim_paused(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_sim_paused) + sizeof(api->get_sim_paused)
        && api->get_sim_paused != NULL;
}
static inline bool piergo_call_get_sim_paused(const PierApi* api)
{
    return api->get_sim_paused();
}

static inline bool piergo_has_spawn_particle(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, spawn_particle) + sizeof(api->spawn_particle)
        && api->spawn_particle != NULL;
}
static inline bool piergo_call_spawn_particle(const PierApi* api, int32_t a0, PierStr a1, double a2, double a3, double a4)
{
    return api->spawn_particle(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_get_player_position(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_player_position) + sizeof(api->get_player_position)
        && api->get_player_position != NULL;
}
static inline PierPlayerPos piergo_call_get_player_position(const PierApi* api, PierStr a0)
{
    return api->get_player_position(a0);
}

static inline bool piergo_has_scan_region(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, scan_region) + sizeof(api->scan_region)
        && api->scan_region != NULL;
}
static inline bool piergo_call_scan_region(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, void* a7, PierBlockSink a8, PierEntitySink a9)
{
    return api->scan_region(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static inline bool piergo_has_get_block(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_block) + sizeof(api->get_block)
        && api->get_block != NULL;
}
static inline bool piergo_call_get_block(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierBlockSink a5)
{
    return api->get_block(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_set_block(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_block) + sizeof(api->set_block)
        && api->set_block != NULL;
}
static inline bool piergo_call_set_block(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4)
{
    return api->set_block(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_get_time(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_time) + sizeof(api->get_time)
        && api->get_time != NULL;
}
static inline bool piergo_call_get_time(const PierApi* api, int64_t* a0)
{
    return api->get_time(a0);
}

static inline bool piergo_has_set_time(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_time) + sizeof(api->set_time)
        && api->set_time != NULL;
}
static inline bool piergo_call_set_time(const PierApi* api, int64_t a0)
{
    return api->set_time(a0);
}

static inline bool piergo_has_set_weather(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_weather) + sizeof(api->set_weather)
        && api->set_weather != NULL;
}
static inline bool piergo_call_set_weather(const PierApi* api, int32_t a0)
{
    return api->set_weather(a0);
}

static inline bool piergo_has_list_players(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, list_players) + sizeof(api->list_players)
        && api->list_players != NULL;
}
static inline void piergo_call_list_players(const PierApi* api, void* a0, PierStrSink a1)
{
    api->list_players(a0, a1);
}

static inline bool piergo_has_player_resolve(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_resolve) + sizeof(api->player_resolve)
        && api->player_resolve != NULL;
}
static inline bool piergo_call_player_resolve(const PierApi* api, PierPlayerSel a0, PierActorId* a1)
{
    return api->player_resolve(a0, a1);
}

static inline bool piergo_has_player_send_message(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_send_message) + sizeof(api->player_send_message)
        && api->player_send_message != NULL;
}
static inline bool piergo_call_player_send_message(const PierApi* api, PierPlayerSel a0, PierStr a1)
{
    return api->player_send_message(a0, a1);
}

static inline bool piergo_has_player_disconnect(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_disconnect) + sizeof(api->player_disconnect)
        && api->player_disconnect != NULL;
}
static inline bool piergo_call_player_disconnect(const PierApi* api, PierPlayerSel a0, PierStr a1)
{
    return api->player_disconnect(a0, a1);
}

static inline bool piergo_has_broadcast_message(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, broadcast_message) + sizeof(api->broadcast_message)
        && api->broadcast_message != NULL;
}
static inline void piergo_call_broadcast_message(const PierApi* api, PierStr a0)
{
    api->broadcast_message(a0);
}

static inline bool piergo_has_player_set_gamemode(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_set_gamemode) + sizeof(api->player_set_gamemode)
        && api->player_set_gamemode != NULL;
}
static inline bool piergo_call_player_set_gamemode(const PierApi* api, PierPlayerSel a0, int32_t a1)
{
    return api->player_set_gamemode(a0, a1);
}

static inline bool piergo_has_player_teleport(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_teleport) + sizeof(api->player_teleport)
        && api->player_teleport != NULL;
}
static inline bool piergo_call_player_teleport(const PierApi* api, PierPlayerSel a0, int32_t a1, double a2, double a3, double a4)
{
    return api->player_teleport(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_player_get_num(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_num) + sizeof(api->player_get_num)
        && api->player_get_num != NULL;
}
static inline bool piergo_call_player_get_num(const PierApi* api, PierPlayerSel a0, int32_t a1, double* a2)
{
    return api->player_get_num(a0, a1, a2);
}

static inline bool piergo_has_player_get_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_str) + sizeof(api->player_get_str)
        && api->player_get_str != NULL;
}
static inline bool piergo_call_player_get_str(const PierApi* api, PierPlayerSel a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->player_get_str(a0, a1, a2, a3);
}

static inline bool piergo_has_player_set_num(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_set_num) + sizeof(api->player_set_num)
        && api->player_set_num != NULL;
}
static inline bool piergo_call_player_set_num(const PierApi* api, PierPlayerSel a0, int32_t a1, double a2)
{
    return api->player_set_num(a0, a1, a2);
}

static inline bool piergo_has_player_action(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_action) + sizeof(api->player_action)
        && api->player_action != NULL;
}
static inline bool piergo_call_player_action(const PierApi* api, PierPlayerSel a0, int32_t a1, PierStr a2, double a3, double a4, double a5, void* a6, PierStrSink a7)
{
    return api->player_action(a0, a1, a2, a3, a4, a5, a6, a7);
}

static inline bool piergo_has_list_actors(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, list_actors) + sizeof(api->list_actors)
        && api->list_actors != NULL;
}
static inline void piergo_call_list_actors(const PierApi* api, int32_t a0, void* a1, PierActorSink a2)
{
    api->list_actors(a0, a1, a2);
}

static inline bool piergo_has_actor_snapshot(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_snapshot) + sizeof(api->actor_snapshot)
        && api->actor_snapshot != NULL;
}
static inline bool piergo_call_actor_snapshot(const PierApi* api, PierActorId a0, void* a1, PierStrSink a2)
{
    return api->actor_snapshot(a0, a1, a2);
}

static inline bool piergo_has_actor_get_num(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_num) + sizeof(api->actor_get_num)
        && api->actor_get_num != NULL;
}
static inline bool piergo_call_actor_get_num(const PierApi* api, PierActorId a0, int32_t a1, double* a2)
{
    return api->actor_get_num(a0, a1, a2);
}

static inline bool piergo_has_actor_get_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_str) + sizeof(api->actor_get_str)
        && api->actor_get_str != NULL;
}
static inline bool piergo_call_actor_get_str(const PierApi* api, PierActorId a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->actor_get_str(a0, a1, a2, a3);
}

static inline bool piergo_has_actor_action(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_action) + sizeof(api->actor_action)
        && api->actor_action != NULL;
}
static inline bool piergo_call_actor_action(const PierApi* api, PierActorId a0, int32_t a1, PierStr a2, double a3, double a4, double a5, void* a6, PierStrSink a7)
{
    return api->actor_action(a0, a1, a2, a3, a4, a5, a6, a7);
}

static inline bool piergo_has_spawn_mob(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, spawn_mob) + sizeof(api->spawn_mob)
        && api->spawn_mob != NULL;
}
static inline bool piergo_call_spawn_mob(const PierApi* api, int32_t a0, PierStr a1, double a2, double a3, double a4, PierActorId* a5)
{
    return api->spawn_mob(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_explode(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, explode) + sizeof(api->explode)
        && api->explode != NULL;
}
static inline bool piergo_call_explode(const PierApi* api, int32_t a0, double a1, double a2, double a3, float a4, float a5, PierActorId a6, bool a7, bool a8, bool a9)
{
    return api->explode(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static inline bool piergo_has_block_get_num(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_get_num) + sizeof(api->block_get_num)
        && api->block_get_num != NULL;
}
static inline bool piergo_call_block_get_num(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, double* a5)
{
    return api->block_get_num(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_block_get_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_get_str) + sizeof(api->block_get_str)
        && api->block_get_str != NULL;
}
static inline bool piergo_call_block_get_str(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, void* a5, PierStrSink a6)
{
    return api->block_get_str(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_block_action(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_action) + sizeof(api->block_action)
        && api->block_action != NULL;
}
static inline bool piergo_call_block_action(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, PierStr a5, void* a6, PierStrSink a7)
{
    return api->block_action(a0, a1, a2, a3, a4, a5, a6, a7);
}

static inline bool piergo_has_block_entity_snbt(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_entity_snbt) + sizeof(api->block_entity_snbt)
        && api->block_entity_snbt != NULL;
}
static inline bool piergo_call_block_entity_snbt(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierStrSink a5)
{
    return api->block_entity_snbt(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_item_get_num(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_get_num) + sizeof(api->item_get_num)
        && api->item_get_num != NULL;
}
static inline bool piergo_call_item_get_num(const PierApi* api, PierStr a0, int32_t a1, double* a2)
{
    return api->item_get_num(a0, a1, a2);
}

static inline bool piergo_has_item_get_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_get_str) + sizeof(api->item_get_str)
        && api->item_get_str != NULL;
}
static inline bool piergo_call_item_get_str(const PierApi* api, PierStr a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->item_get_str(a0, a1, a2, a3);
}

static inline bool piergo_has_item_transform(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_transform) + sizeof(api->item_transform)
        && api->item_transform != NULL;
}
static inline bool piergo_call_item_transform(const PierApi* api, PierStr a0, int32_t a1, PierStr a2, double a3, void* a4, PierStrSink a5)
{
    return api->item_transform(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_container_size(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_size) + sizeof(api->container_size)
        && api->container_size != NULL;
}
static inline bool piergo_call_container_size(const PierApi* api, PierContainerRef a0, int32_t* a1)
{
    return api->container_size(a0, a1);
}

static inline bool piergo_has_container_get_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_get_item) + sizeof(api->container_get_item)
        && api->container_get_item != NULL;
}
static inline bool piergo_call_container_get_item(const PierApi* api, PierContainerRef a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->container_get_item(a0, a1, a2, a3);
}

static inline bool piergo_has_container_set_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_set_item) + sizeof(api->container_set_item)
        && api->container_set_item != NULL;
}
static inline bool piergo_call_container_set_item(const PierApi* api, PierContainerRef a0, int32_t a1, PierStr a2)
{
    return api->container_set_item(a0, a1, a2);
}

static inline bool piergo_has_container_add_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_add_item) + sizeof(api->container_add_item)
        && api->container_add_item != NULL;
}
static inline bool piergo_call_container_add_item(const PierApi* api, PierContainerRef a0, PierStr a1)
{
    return api->container_add_item(a0, a1);
}

static inline bool piergo_has_container_remove_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_remove_item) + sizeof(api->container_remove_item)
        && api->container_remove_item != NULL;
}
static inline bool piergo_call_container_remove_item(const PierApi* api, PierContainerRef a0, int32_t a1, int32_t a2)
{
    return api->container_remove_item(a0, a1, a2);
}

static inline bool piergo_has_container_clear(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_clear) + sizeof(api->container_clear)
        && api->container_clear != NULL;
}
static inline bool piergo_call_container_clear(const PierApi* api, PierContainerRef a0)
{
    return api->container_clear(a0);
}

static inline bool piergo_has_scoreboard_op(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, scoreboard_op) + sizeof(api->scoreboard_op)
        && api->scoreboard_op != NULL;
}
static inline bool piergo_call_scoreboard_op(const PierApi* api, int32_t a0, PierStr a1, PierStr a2, int64_t a3, void* a4, PierStrSink a5)
{
    return api->scoreboard_op(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_form_send(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, form_send) + sizeof(api->form_send)
        && api->form_send != NULL;
}
static inline bool piergo_call_form_send(const PierApi* api, PierModHandle a0, PierPlayerSel a1, int32_t a2, PierStr a3, PierFormResultCb a4, void* a5)
{
    return api->form_send(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_register_command_ex(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, register_command_ex) + sizeof(api->register_command_ex)
        && api->register_command_ex != NULL;
}
static inline bool piergo_call_register_command_ex(const PierApi* api, PierModHandle a0, PierStr a1, PierStr a2, int32_t a3, PierStr a4, PierCommandCb a5, void* a6)
{
    return api->register_command_ex(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_register_command_enum(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, register_command_enum) + sizeof(api->register_command_enum)
        && api->register_command_enum != NULL;
}
static inline bool piergo_call_register_command_enum(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->register_command_enum(a0, a1);
}

static inline bool piergo_has_register_command_soft_enum(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, register_command_soft_enum) + sizeof(api->register_command_soft_enum)
        && api->register_command_soft_enum != NULL;
}
static inline bool piergo_call_register_command_soft_enum(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->register_command_soft_enum(a0, a1);
}

static inline bool piergo_has_update_command_soft_enum(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, update_command_soft_enum) + sizeof(api->update_command_soft_enum)
        && api->update_command_soft_enum != NULL;
}
static inline bool piergo_call_update_command_soft_enum(const PierApi* api, PierStr a0, int32_t a1, PierStr a2)
{
    return api->update_command_soft_enum(a0, a1, a2);
}

static inline bool piergo_has_nbt_snbt_to_binary(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, nbt_snbt_to_binary) + sizeof(api->nbt_snbt_to_binary)
        && api->nbt_snbt_to_binary != NULL;
}
static inline bool piergo_call_nbt_snbt_to_binary(const PierApi* api, PierStr a0, int32_t a1, void* a2, PierBytesSink a3)
{
    return api->nbt_snbt_to_binary(a0, a1, a2, a3);
}

static inline bool piergo_has_nbt_binary_to_snbt(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, nbt_binary_to_snbt) + sizeof(api->nbt_binary_to_snbt)
        && api->nbt_binary_to_snbt != NULL;
}
static inline bool piergo_call_nbt_binary_to_snbt(const PierApi* api, uint8_t const* a0, size_t a1, int32_t a2, void* a3, PierStrSink a4)
{
    return api->nbt_binary_to_snbt(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_kvdb_open(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_open) + sizeof(api->kvdb_open)
        && api->kvdb_open != NULL;
}
static inline PierKvDbHandle piergo_call_kvdb_open(const PierApi* api, PierModHandle a0, PierStr a1, bool a2)
{
    return api->kvdb_open(a0, a1, a2);
}

static inline bool piergo_has_kvdb_close(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_close) + sizeof(api->kvdb_close)
        && api->kvdb_close != NULL;
}
static inline void piergo_call_kvdb_close(const PierApi* api, PierKvDbHandle a0)
{
    api->kvdb_close(a0);
}

static inline bool piergo_has_kvdb_get(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_get) + sizeof(api->kvdb_get)
        && api->kvdb_get != NULL;
}
static inline bool piergo_call_kvdb_get(const PierApi* api, PierKvDbHandle a0, PierStr a1, void* a2, PierStrSink a3)
{
    return api->kvdb_get(a0, a1, a2, a3);
}

static inline bool piergo_has_kvdb_set(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_set) + sizeof(api->kvdb_set)
        && api->kvdb_set != NULL;
}
static inline bool piergo_call_kvdb_set(const PierApi* api, PierKvDbHandle a0, PierStr a1, PierStr a2)
{
    return api->kvdb_set(a0, a1, a2);
}

static inline bool piergo_has_kvdb_del(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_del) + sizeof(api->kvdb_del)
        && api->kvdb_del != NULL;
}
static inline bool piergo_call_kvdb_del(const PierApi* api, PierKvDbHandle a0, PierStr a1)
{
    return api->kvdb_del(a0, a1);
}

static inline bool piergo_has_kvdb_has(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_has) + sizeof(api->kvdb_has)
        && api->kvdb_has != NULL;
}
static inline bool piergo_call_kvdb_has(const PierApi* api, PierKvDbHandle a0, PierStr a1)
{
    return api->kvdb_has(a0, a1);
}

static inline bool piergo_has_kvdb_is_empty(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_is_empty) + sizeof(api->kvdb_is_empty)
        && api->kvdb_is_empty != NULL;
}
static inline bool piergo_call_kvdb_is_empty(const PierApi* api, PierKvDbHandle a0)
{
    return api->kvdb_is_empty(a0);
}

static inline bool piergo_has_kvdb_iter(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, kvdb_iter) + sizeof(api->kvdb_iter)
        && api->kvdb_iter != NULL;
}
static inline void piergo_call_kvdb_iter(const PierApi* api, PierKvDbHandle a0, void* a1, PierKvSink a2)
{
    api->kvdb_iter(a0, a1, a2);
}

static inline bool piergo_has_sys_info_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sys_info_str) + sizeof(api->sys_info_str)
        && api->sys_info_str != NULL;
}
static inline bool piergo_call_sys_info_str(const PierApi* api, int32_t a0, void* a1, PierStrSink a2)
{
    return api->sys_info_str(a0, a1, a2);
}

static inline bool piergo_has_sys_get_env(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sys_get_env) + sizeof(api->sys_get_env)
        && api->sys_get_env != NULL;
}
static inline bool piergo_call_sys_get_env(const PierApi* api, PierStr a0, void* a1, PierStrSink a2)
{
    return api->sys_get_env(a0, a1, a2);
}

static inline bool piergo_has_sys_set_env(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sys_set_env) + sizeof(api->sys_set_env)
        && api->sys_set_env != NULL;
}
static inline bool piergo_call_sys_set_env(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->sys_set_env(a0, a1);
}

static inline bool piergo_has_sys_is_wine(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sys_is_wine) + sizeof(api->sys_is_wine)
        && api->sys_is_wine != NULL;
}
static inline bool piergo_call_sys_is_wine(const PierApi* api)
{
    return api->sys_is_wine();
}

static inline bool piergo_has_get_difficulty(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_difficulty) + sizeof(api->get_difficulty)
        && api->get_difficulty != NULL;
}
static inline bool piergo_call_get_difficulty(const PierApi* api, int32_t* a0)
{
    return api->get_difficulty(a0);
}

static inline bool piergo_has_set_difficulty(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_difficulty) + sizeof(api->set_difficulty)
        && api->set_difficulty != NULL;
}
static inline bool piergo_call_set_difficulty(const PierApi* api, int32_t a0)
{
    return api->set_difficulty(a0);
}

static inline bool piergo_has_get_seed(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_seed) + sizeof(api->get_seed)
        && api->get_seed != NULL;
}
static inline bool piergo_call_get_seed(const PierApi* api, int64_t* a0)
{
    return api->get_seed(a0);
}

static inline bool piergo_has_game_rule_get(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, game_rule_get) + sizeof(api->game_rule_get)
        && api->game_rule_get != NULL;
}
static inline bool piergo_call_game_rule_get(const PierApi* api, PierStr a0, void* a1, PierStrSink a2)
{
    return api->game_rule_get(a0, a1, a2);
}

static inline bool piergo_has_game_rule_set(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, game_rule_set) + sizeof(api->game_rule_set)
        && api->game_rule_set != NULL;
}
static inline bool piergo_call_game_rule_set(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->game_rule_set(a0, a1);
}

static inline bool piergo_has_server_info_str(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, server_info_str) + sizeof(api->server_info_str)
        && api->server_info_str != NULL;
}
static inline bool piergo_call_server_info_str(const PierApi* api, int32_t a0, void* a1, PierStrSink a2)
{
    return api->server_info_str(a0, a1, a2);
}

static inline bool piergo_has_spawn_particle_for(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, spawn_particle_for) + sizeof(api->spawn_particle_for)
        && api->spawn_particle_for != NULL;
}
static inline bool piergo_call_spawn_particle_for(const PierApi* api, PierPlayerSel a0, int32_t a1, PierStr a2, double a3, double a4, double a5)
{
    return api->spawn_particle_for(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_send_packet(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, send_packet) + sizeof(api->send_packet)
        && api->send_packet != NULL;
}
static inline bool piergo_call_send_packet(const PierApi* api, PierPlayerSel a0, int32_t a1, uint8_t const* a2, size_t a3)
{
    return api->send_packet(a0, a1, a2, a3);
}

static inline bool piergo_has_tick_freeze(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, tick_freeze) + sizeof(api->tick_freeze)
        && api->tick_freeze != NULL;
}
static inline bool piergo_call_tick_freeze(const PierApi* api, bool a0)
{
    return api->tick_freeze(a0);
}

static inline bool piergo_has_tick_step(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, tick_step) + sizeof(api->tick_step)
        && api->tick_step != NULL;
}
static inline bool piergo_call_tick_step(const PierApi* api, uint32_t a0)
{
    return api->tick_step(a0);
}

static inline bool piergo_has_tick_warp(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, tick_warp) + sizeof(api->tick_warp)
        && api->tick_warp != NULL;
}
static inline bool piergo_call_tick_warp(const PierApi* api, double a0)
{
    return api->tick_warp(a0);
}

static inline bool piergo_has_profile_begin(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, profile_begin) + sizeof(api->profile_begin)
        && api->profile_begin != NULL;
}
static inline bool piergo_call_profile_begin(const PierApi* api, uint32_t a0)
{
    return api->profile_begin(a0);
}

static inline bool piergo_has_profile_take(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, profile_take) + sizeof(api->profile_take)
        && api->profile_take != NULL;
}
static inline bool piergo_call_profile_take(const PierApi* api, void* a0, PierStrSink a1)
{
    return api->profile_take(a0, a1);
}

static inline bool piergo_has_sim_spawn(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sim_spawn) + sizeof(api->sim_spawn)
        && api->sim_spawn != NULL;
}
static inline bool piergo_call_sim_spawn(const PierApi* api, PierStr a0, int32_t a1, double a2, double a3, double a4)
{
    return api->sim_spawn(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_sim_do(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sim_do) + sizeof(api->sim_do)
        && api->sim_do != NULL;
}
static inline bool piergo_call_sim_do(const PierApi* api, PierPlayerSel a0, PierStr a1, PierStr a2)
{
    return api->sim_do(a0, a1, a2);
}

static inline bool piergo_has_sim_is(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sim_is) + sizeof(api->sim_is)
        && api->sim_is != NULL;
}
static inline bool piergo_call_sim_is(const PierApi* api, PierPlayerSel a0)
{
    return api->sim_is(a0);
}

static inline bool piergo_has_sim_list(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, sim_list) + sizeof(api->sim_list)
        && api->sim_list != NULL;
}
static inline void piergo_call_sim_list(const PierApi* api, void* a0, PierStrSink a1)
{
    api->sim_list(a0, a1);
}

static inline bool piergo_has_villages(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, villages) + sizeof(api->villages)
        && api->villages != NULL;
}
static inline void piergo_call_villages(const PierApi* api, int32_t a0, void* a1, PierStrSink a2)
{
    api->villages(a0, a1, a2);
}

static inline bool piergo_has_structures_near(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, structures_near) + sizeof(api->structures_near)
        && api->structures_near != NULL;
}
static inline void piergo_call_structures_near(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, void* a5, PierStrSink a6)
{
    api->structures_near(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_player_send_message_typed(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_send_message_typed) + sizeof(api->player_send_message_typed)
        && api->player_send_message_typed != NULL;
}
static inline bool piergo_call_player_send_message_typed(const PierApi* api, PierPlayerSel a0, PierStr a1, int32_t a2)
{
    return api->player_send_message_typed(a0, a1, a2);
}

static inline bool piergo_has_get_money(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_money) + sizeof(api->get_money)
        && api->get_money != NULL;
}
static inline int64_t piergo_call_get_money(const PierApi* api, PierStr a0)
{
    return api->get_money(a0);
}

static inline bool piergo_has_set_money(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_money) + sizeof(api->set_money)
        && api->set_money != NULL;
}
static inline bool piergo_call_set_money(const PierApi* api, PierStr a0, int64_t a1)
{
    return api->set_money(a0, a1);
}

static inline bool piergo_has_add_money(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, add_money) + sizeof(api->add_money)
        && api->add_money != NULL;
}
static inline bool piergo_call_add_money(const PierApi* api, PierStr a0, int64_t a1)
{
    return api->add_money(a0, a1);
}

static inline bool piergo_has_reduce_money(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, reduce_money) + sizeof(api->reduce_money)
        && api->reduce_money != NULL;
}
static inline bool piergo_call_reduce_money(const PierApi* api, PierStr a0, int64_t a1)
{
    return api->reduce_money(a0, a1);
}

static inline bool piergo_has_trans_money(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, trans_money) + sizeof(api->trans_money)
        && api->trans_money != NULL;
}
static inline bool piergo_call_trans_money(const PierApi* api, PierStr a0, PierStr a1, int64_t a2, PierStr a3)
{
    return api->trans_money(a0, a1, a2, a3);
}

static inline bool piergo_has_money_get_hist(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, money_get_hist) + sizeof(api->money_get_hist)
        && api->money_get_hist != NULL;
}
static inline void piergo_call_money_get_hist(const PierApi* api, PierStr a0, int32_t a1, void* a2, PierStrSink a3)
{
    api->money_get_hist(a0, a1, a2, a3);
}

static inline bool piergo_has_money_clear_hist(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, money_clear_hist) + sizeof(api->money_clear_hist)
        && api->money_clear_hist != NULL;
}
static inline void piergo_call_money_clear_hist(const PierApi* api, int32_t a0)
{
    api->money_clear_hist(a0);
}

static inline bool piergo_has_money_listen_before_event(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, money_listen_before_event) + sizeof(api->money_listen_before_event)
        && api->money_listen_before_event != NULL;
}
static inline void piergo_call_money_listen_before_event(const PierApi* api, PierMoneyCb a0)
{
    api->money_listen_before_event(a0);
}

static inline bool piergo_has_money_listen_after_event(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, money_listen_after_event) + sizeof(api->money_listen_after_event)
        && api->money_listen_after_event != NULL;
}
static inline void piergo_call_money_listen_after_event(const PierApi* api, PierMoneyCb a0)
{
    api->money_listen_after_event(a0);
}

static inline bool piergo_has_money_ranking(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, money_ranking) + sizeof(api->money_ranking)
        && api->money_ranking != NULL;
}
static inline void piergo_call_money_ranking(const PierApi* api, uint16_t a0, void* a1, PierStrSink a2)
{
    api->money_ranking(a0, a1, a2);
}

static inline bool piergo_has_player_get_carried_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_carried_item) + sizeof(api->player_get_carried_item)
        && api->player_get_carried_item != NULL;
}
static inline bool piergo_call_player_get_carried_item(const PierApi* api, PierPlayerSel a0, void* a1, PierStrSink a2)
{
    return api->player_get_carried_item(a0, a1, a2);
}

static inline bool piergo_has_player_get_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_item) + sizeof(api->player_get_item)
        && api->player_get_item != NULL;
}
static inline bool piergo_call_player_get_item(const PierApi* api, PierPlayerSel a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->player_get_item(a0, a1, a2, a3);
}

static inline bool piergo_has_player_set_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_set_item) + sizeof(api->player_set_item)
        && api->player_set_item != NULL;
}
static inline bool piergo_call_player_set_item(const PierApi* api, PierPlayerSel a0, int32_t a1, PierStr a2)
{
    return api->player_set_item(a0, a1, a2);
}

static inline bool piergo_has_player_get_equipment(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_equipment) + sizeof(api->player_get_equipment)
        && api->player_get_equipment != NULL;
}
static inline bool piergo_call_player_get_equipment(const PierApi* api, PierPlayerSel a0, void* a1, PierStrSink a2)
{
    return api->player_get_equipment(a0, a1, a2);
}

static inline bool piergo_has_player_get_cooldown(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_cooldown) + sizeof(api->player_get_cooldown)
        && api->player_get_cooldown != NULL;
}
static inline int32_t piergo_call_player_get_cooldown(const PierApi* api, PierPlayerSel a0, PierStr a1)
{
    return api->player_get_cooldown(a0, a1);
}

static inline bool piergo_has_player_start_cooldown(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_start_cooldown) + sizeof(api->player_start_cooldown)
        && api->player_start_cooldown != NULL;
}
static inline bool piergo_call_player_start_cooldown(const PierApi* api, PierPlayerSel a0, PierStr a1, int32_t a2)
{
    return api->player_start_cooldown(a0, a1, a2);
}

static inline bool piergo_has_player_get_network_status(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_get_network_status) + sizeof(api->player_get_network_status)
        && api->player_get_network_status != NULL;
}
static inline bool piergo_call_player_get_network_status(const PierApi* api, PierPlayerSel a0, void* a1, PierStrSink a2)
{
    return api->player_get_network_status(a0, a1, a2);
}

static inline bool piergo_has_actor_get_vehicle(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_vehicle) + sizeof(api->actor_get_vehicle)
        && api->actor_get_vehicle != NULL;
}
static inline bool piergo_call_actor_get_vehicle(const PierApi* api, PierActorId a0, PierActorId* a1)
{
    return api->actor_get_vehicle(a0, a1);
}

static inline bool piergo_has_actor_get_first_passenger(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_first_passenger) + sizeof(api->actor_get_first_passenger)
        && api->actor_get_first_passenger != NULL;
}
static inline bool piergo_call_actor_get_first_passenger(const PierApi* api, PierActorId a0, PierActorId* a1)
{
    return api->actor_get_first_passenger(a0, a1);
}

static inline bool piergo_has_actor_get_owner(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_owner) + sizeof(api->actor_get_owner)
        && api->actor_get_owner != NULL;
}
static inline bool piergo_call_actor_get_owner(const PierApi* api, PierActorId a0, PierActorId* a1)
{
    return api->actor_get_owner(a0, a1);
}

static inline bool piergo_has_actor_get_target(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_target) + sizeof(api->actor_get_target)
        && api->actor_get_target != NULL;
}
static inline bool piergo_call_actor_get_target(const PierApi* api, PierActorId a0, PierActorId* a1)
{
    return api->actor_get_target(a0, a1);
}

static inline bool piergo_has_actor_get_equipped_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_equipped_item) + sizeof(api->actor_get_equipped_item)
        && api->actor_get_equipped_item != NULL;
}
static inline bool piergo_call_actor_get_equipped_item(const PierApi* api, PierActorId a0, int32_t a1, void* a2, PierStrSink a3)
{
    return api->actor_get_equipped_item(a0, a1, a2, a3);
}

static inline bool piergo_has_actor_set_equipped_item(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_set_equipped_item) + sizeof(api->actor_set_equipped_item)
        && api->actor_set_equipped_item != NULL;
}
static inline bool piergo_call_actor_set_equipped_item(const PierApi* api, PierActorId a0, int32_t a1, PierStr a2)
{
    return api->actor_set_equipped_item(a0, a1, a2);
}

static inline bool piergo_has_actor_get_effects(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_effects) + sizeof(api->actor_get_effects)
        && api->actor_get_effects != NULL;
}
static inline bool piergo_call_actor_get_effects(const PierApi* api, PierActorId a0, void* a1, PierStrSink a2)
{
    return api->actor_get_effects(a0, a1, a2);
}

static inline bool piergo_has_actor_get_status_flag(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_status_flag) + sizeof(api->actor_get_status_flag)
        && api->actor_get_status_flag != NULL;
}
static inline bool piergo_call_actor_get_status_flag(const PierApi* api, PierActorId a0, int32_t a1)
{
    return api->actor_get_status_flag(a0, a1);
}

static inline bool piergo_has_actor_set_status_flag(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_set_status_flag) + sizeof(api->actor_set_status_flag)
        && api->actor_set_status_flag != NULL;
}
static inline bool piergo_call_actor_set_status_flag(const PierApi* api, PierActorId a0, int32_t a1, bool a2)
{
    return api->actor_set_status_flag(a0, a1, a2);
}

static inline bool piergo_has_actor_trace_ray(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_trace_ray) + sizeof(api->actor_trace_ray)
        && api->actor_trace_ray != NULL;
}
static inline bool piergo_call_actor_trace_ray(const PierApi* api, PierActorId a0, float a1, bool a2, bool a3, void* a4, PierStrSink a5)
{
    return api->actor_trace_ray(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_actor_distance_to(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_distance_to) + sizeof(api->actor_distance_to)
        && api->actor_distance_to != NULL;
}
static inline bool piergo_call_actor_distance_to(const PierApi* api, PierActorId a0, PierActorId a1, double* a2)
{
    return api->actor_distance_to(a0, a1, a2);
}

static inline bool piergo_has_actor_get_aabb(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_get_aabb) + sizeof(api->actor_get_aabb)
        && api->actor_get_aabb != NULL;
}
static inline bool piergo_call_actor_get_aabb(const PierApi* api, PierActorId a0, void* a1, PierStrSink a2)
{
    return api->actor_get_aabb(a0, a1, a2);
}

static inline bool piergo_has_actor_clone(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, actor_clone) + sizeof(api->actor_clone)
        && api->actor_clone != NULL;
}
static inline bool piergo_call_actor_clone(const PierApi* api, PierActorId a0, int32_t a1, double a2, double a3, double a4, PierActorId* a5)
{
    return api->actor_clone(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_block_get_state(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_get_state) + sizeof(api->block_get_state)
        && api->block_get_state != NULL;
}
static inline bool piergo_call_block_get_state(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4, void* a5, PierStrSink a6)
{
    return api->block_get_state(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_block_set_state(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_set_state) + sizeof(api->block_set_state)
        && api->block_set_state != NULL;
}
static inline bool piergo_call_block_set_state(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4, PierStr a5)
{
    return api->block_set_state(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_block_get_collision_shape(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, block_get_collision_shape) + sizeof(api->block_get_collision_shape)
        && api->block_get_collision_shape != NULL;
}
static inline bool piergo_call_block_get_collision_shape(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierStrSink a5)
{
    return api->block_get_collision_shape(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_item_get_enchants(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_get_enchants) + sizeof(api->item_get_enchants)
        && api->item_get_enchants != NULL;
}
static inline bool piergo_call_item_get_enchants(const PierApi* api, PierStr a0, void* a1, PierStrSink a2)
{
    return api->item_get_enchants(a0, a1, a2);
}

static inline bool piergo_has_item_set_enchants(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_set_enchants) + sizeof(api->item_set_enchants)
        && api->item_set_enchants != NULL;
}
static inline bool piergo_call_item_set_enchants(const PierApi* api, PierStr a0, PierStr a1, void* a2, PierStrSink a3)
{
    return api->item_set_enchants(a0, a1, a2, a3);
}

static inline bool piergo_has_item_matches(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_matches) + sizeof(api->item_matches)
        && api->item_matches != NULL;
}
static inline bool piergo_call_item_matches(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->item_matches(a0, a1);
}

static inline bool piergo_has_item_get_user_data(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, item_get_user_data) + sizeof(api->item_get_user_data)
        && api->item_get_user_data != NULL;
}
static inline bool piergo_call_item_get_user_data(const PierApi* api, PierStr a0, void* a1, PierStrSink a2)
{
    return api->item_get_user_data(a0, a1, a2);
}

static inline bool piergo_has_level_get_biome(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_get_biome) + sizeof(api->level_get_biome)
        && api->level_get_biome != NULL;
}
static inline bool piergo_call_level_get_biome(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierStrSink a5)
{
    return api->level_get_biome(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_level_get_default_spawn(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_get_default_spawn) + sizeof(api->level_get_default_spawn)
        && api->level_get_default_spawn != NULL;
}
static inline bool piergo_call_level_get_default_spawn(const PierApi* api, int32_t* a0, int32_t* a1, int32_t* a2)
{
    return api->level_get_default_spawn(a0, a1, a2);
}

static inline bool piergo_has_level_set_default_spawn(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_set_default_spawn) + sizeof(api->level_set_default_spawn)
        && api->level_set_default_spawn != NULL;
}
static inline bool piergo_call_level_set_default_spawn(const PierApi* api, int32_t a0, int32_t a1, int32_t a2)
{
    return api->level_set_default_spawn(a0, a1, a2);
}

static inline bool piergo_has_level_save(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_save) + sizeof(api->level_save)
        && api->level_save != NULL;
}
static inline bool piergo_call_level_save(const PierApi* api)
{
    return api->level_save();
}

static inline bool piergo_has_level_get_sleep_status(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_get_sleep_status) + sizeof(api->level_get_sleep_status)
        && api->level_get_sleep_status != NULL;
}
static inline bool piergo_call_level_get_sleep_status(const PierApi* api, void* a0, PierStrSink a1)
{
    return api->level_get_sleep_status(a0, a1);
}

static inline bool piergo_has_level_update_weather(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_update_weather) + sizeof(api->level_update_weather)
        && api->level_update_weather != NULL;
}
static inline bool piergo_call_level_update_weather(const PierApi* api, float a0, int32_t a1, float a2, int32_t a3)
{
    return api->level_update_weather(a0, a1, a2, a3);
}

static inline bool piergo_has_level_find_path(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_find_path) + sizeof(api->level_find_path)
        && api->level_find_path != NULL;
}
static inline bool piergo_call_level_find_path(const PierApi* api, PierActorId a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierStrSink a5)
{
    return api->level_find_path(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_packet_hook_register(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, packet_hook_register) + sizeof(api->packet_hook_register)
        && api->packet_hook_register != NULL;
}
static inline PierPacketHookHandle piergo_call_packet_hook_register(const PierApi* api, PierModHandle a0, int32_t a1, PierPacketCb a2, void* a3)
{
    return api->packet_hook_register(a0, a1, a2, a3);
}

static inline bool piergo_has_packet_hook_unregister(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, packet_hook_unregister) + sizeof(api->packet_hook_unregister)
        && api->packet_hook_unregister != NULL;
}
static inline bool piergo_call_packet_hook_unregister(const PierApi* api, PierModHandle a0, PierPacketHookHandle a1)
{
    return api->packet_hook_unregister(a0, a1);
}

static inline bool piergo_has_packet_conn_hook_register(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, packet_conn_hook_register) + sizeof(api->packet_conn_hook_register)
        && api->packet_conn_hook_register != NULL;
}
static inline PierPacketHookHandle piergo_call_packet_conn_hook_register(const PierApi* api, PierModHandle a0, PierConnCb a1, void* a2)
{
    return api->packet_conn_hook_register(a0, a1, a2);
}

static inline bool piergo_has_packet_conn_hook_unregister(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, packet_conn_hook_unregister) + sizeof(api->packet_conn_hook_unregister)
        && api->packet_conn_hook_unregister != NULL;
}
static inline bool piergo_call_packet_conn_hook_unregister(const PierApi* api, PierModHandle a0, PierPacketHookHandle a1)
{
    return api->packet_conn_hook_unregister(a0, a1);
}

static inline bool piergo_has_client_get_local_player(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_get_local_player) + sizeof(api->client_get_local_player)
        && api->client_get_local_player != NULL;
}
static inline bool piergo_call_client_get_local_player(const PierApi* api, void* a0, PierStrSink a1)
{
    return api->client_get_local_player(a0, a1);
}

static inline bool piergo_has_client_is_in_level(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_is_in_level) + sizeof(api->client_is_in_level)
        && api->client_is_in_level != NULL;
}
static inline bool piergo_call_client_is_in_level(const PierApi* api)
{
    return api->client_is_in_level();
}

static inline bool piergo_has_client_get_screen_name(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_get_screen_name) + sizeof(api->client_get_screen_name)
        && api->client_get_screen_name != NULL;
}
static inline bool piergo_call_client_get_screen_name(const PierApi* api, void* a0, PierStrSink a1)
{
    return api->client_get_screen_name(a0, a1);
}

static inline bool piergo_has_client_register_key(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_register_key) + sizeof(api->client_register_key)
        && api->client_register_key != NULL;
}
static inline PierKeyHandle piergo_call_client_register_key(const PierApi* api, PierModHandle a0, PierStr a1, int32_t const* a2, int32_t a3, bool a4, PierKeyCb a5, PierKeyCb a6, void* a7)
{
    return api->client_register_key(a0, a1, a2, a3, a4, a5, a6, a7);
}

static inline bool piergo_has_client_unregister_key(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_unregister_key) + sizeof(api->client_unregister_key)
        && api->client_unregister_key != NULL;
}
static inline bool piergo_call_client_unregister_key(const PierApi* api, PierKeyHandle a0)
{
    return api->client_unregister_key(a0);
}

static inline bool piergo_has_client_get_key_codes(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, client_get_key_codes) + sizeof(api->client_get_key_codes)
        && api->client_get_key_codes != NULL;
}
static inline bool piergo_call_client_get_key_codes(const PierApi* api, PierKeyHandle a0, void* a1, PierStrSink a2)
{
    return api->client_get_key_codes(a0, a1, a2);
}

static inline bool piergo_has_md_is_available(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_is_available) + sizeof(api->md_is_available)
        && api->md_is_available != NULL;
}
static inline bool piergo_call_md_is_available(const PierApi* api)
{
    return api->md_is_available();
}

static inline bool piergo_has_md_set_dimension_rule(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_set_dimension_rule) + sizeof(api->md_set_dimension_rule)
        && api->md_set_dimension_rule != NULL;
}
static inline void piergo_call_md_set_dimension_rule(const PierApi* api, int32_t a0, int32_t a1, bool a2)
{
    api->md_set_dimension_rule(a0, a1, a2);
}

static inline bool piergo_has_md_get_dimension_rule(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_get_dimension_rule) + sizeof(api->md_get_dimension_rule)
        && api->md_get_dimension_rule != NULL;
}
static inline bool piergo_call_md_get_dimension_rule(const PierApi* api, int32_t a0, int32_t a1, bool* a2)
{
    return api->md_get_dimension_rule(a0, a1, a2);
}

static inline bool piergo_has_md_clear_dimension_rules(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_clear_dimension_rules) + sizeof(api->md_clear_dimension_rules)
        && api->md_clear_dimension_rules != NULL;
}
static inline void piergo_call_md_clear_dimension_rules(const PierApi* api, int32_t a0)
{
    api->md_clear_dimension_rules(a0);
}

static inline bool piergo_has_md_get_dimension_id(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_get_dimension_id) + sizeof(api->md_get_dimension_id)
        && api->md_get_dimension_id != NULL;
}
static inline int32_t piergo_call_md_get_dimension_id(const PierApi* api, PierStr a0)
{
    return api->md_get_dimension_id(a0);
}

static inline bool piergo_has_schedule_for(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule_for) + sizeof(api->schedule_for)
        && api->schedule_for != NULL;
}
static inline uint64_t piergo_call_schedule_for(const PierApi* api, PierModHandle a0, PierTaskCb a1, void* a2)
{
    return api->schedule_for(a0, a1, a2);
}

static inline bool piergo_has_schedule_after_for(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule_after_for) + sizeof(api->schedule_after_for)
        && api->schedule_after_for != NULL;
}
static inline uint64_t piergo_call_schedule_after_for(const PierApi* api, PierModHandle a0, PierTaskCb a1, void* a2, uint64_t a3)
{
    return api->schedule_after_for(a0, a1, a2, a3);
}

static inline bool piergo_has_schedule_cancel(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule_cancel) + sizeof(api->schedule_cancel)
        && api->schedule_cancel != NULL;
}
static inline bool piergo_call_schedule_cancel(const PierApi* api, PierModHandle a0, uint64_t a1)
{
    return api->schedule_cancel(a0, a1);
}

static inline bool piergo_has_schedule_pending_count(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, schedule_pending_count) + sizeof(api->schedule_pending_count)
        && api->schedule_pending_count != NULL;
}
static inline uint32_t piergo_call_schedule_pending_count(const PierApi* api, PierModHandle a0)
{
    return api->schedule_pending_count(a0);
}

static inline bool piergo_has_container_refresh(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_refresh) + sizeof(api->container_refresh)
        && api->container_refresh != NULL;
}
static inline bool piergo_call_container_refresh(const PierApi* api, PierContainerRef a0)
{
    return api->container_refresh(a0);
}

static inline bool piergo_has_player_send_title(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_send_title) + sizeof(api->player_send_title)
        && api->player_send_title != NULL;
}
static inline bool piergo_call_player_send_title(const PierApi* api, PierPlayerSel a0, int32_t a1, PierStr a2, int32_t a3, int32_t a4, int32_t a5)
{
    return api->player_send_title(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_bus_subscribe(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, bus_subscribe) + sizeof(api->bus_subscribe)
        && api->bus_subscribe != NULL;
}
static inline uint64_t piergo_call_bus_subscribe(const PierApi* api, PierModHandle a0, PierStr a1, PierBusCb a2, void* a3)
{
    return api->bus_subscribe(a0, a1, a2, a3);
}

static inline bool piergo_has_bus_unsubscribe(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, bus_unsubscribe) + sizeof(api->bus_unsubscribe)
        && api->bus_unsubscribe != NULL;
}
static inline bool piergo_call_bus_unsubscribe(const PierApi* api, PierModHandle a0, uint64_t a1)
{
    return api->bus_unsubscribe(a0, a1);
}

static inline bool piergo_has_bus_publish(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, bus_publish) + sizeof(api->bus_publish)
        && api->bus_publish != NULL;
}
static inline uint32_t piergo_call_bus_publish(const PierApi* api, PierModHandle a0, PierStr a1, PierStr a2)
{
    return api->bus_publish(a0, a1, a2);
}

static inline bool piergo_has_bus_publish_vetoable(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, bus_publish_vetoable) + sizeof(api->bus_publish_vetoable)
        && api->bus_publish_vetoable != NULL;
}
static inline bool piergo_call_bus_publish_vetoable(const PierApi* api, PierModHandle a0, PierStr a1, PierStr a2, uint32_t* a3)
{
    return api->bus_publish_vetoable(a0, a1, a2, a3);
}

static inline bool piergo_has_bus_subscriber_count(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, bus_subscriber_count) + sizeof(api->bus_subscriber_count)
        && api->bus_subscriber_count != NULL;
}
static inline uint32_t piergo_call_bus_subscriber_count(const PierApi* api, PierStr a0)
{
    return api->bus_subscriber_count(a0);
}

static inline bool piergo_has_md_set_plot_merges(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_set_plot_merges) + sizeof(api->md_set_plot_merges)
        && api->md_set_plot_merges != NULL;
}
static inline void piergo_call_md_set_plot_merges(const PierApi* api, int32_t a0, int32_t const* a1, int32_t a2)
{
    api->md_set_plot_merges(a0, a1, a2);
}

static inline bool piergo_has_service_register(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, service_register) + sizeof(api->service_register)
        && api->service_register != NULL;
}
static inline uint64_t piergo_call_service_register(const PierApi* api, PierModHandle a0, PierStr a1, PierServiceCb a2, void* a3)
{
    return api->service_register(a0, a1, a2, a3);
}

static inline bool piergo_has_service_unregister(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, service_unregister) + sizeof(api->service_unregister)
        && api->service_unregister != NULL;
}
static inline bool piergo_call_service_unregister(const PierApi* api, PierModHandle a0, uint64_t a1)
{
    return api->service_unregister(a0, a1);
}

static inline bool piergo_has_service_call(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, service_call) + sizeof(api->service_call)
        && api->service_call != NULL;
}
static inline int32_t piergo_call_service_call(const PierApi* api, PierModHandle a0, PierStr a1, PierStr a2, void* a3, PierStrSink a4)
{
    return api->service_call(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_service_list(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, service_list) + sizeof(api->service_list)
        && api->service_list != NULL;
}
static inline void piergo_call_service_list(const PierApi* api, void* a0, PierStrSink a1)
{
    api->service_list(a0, a1);
}

static inline bool piergo_has_edit_set_block_nbt(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_set_block_nbt) + sizeof(api->edit_set_block_nbt)
        && api->edit_set_block_nbt != NULL;
}
static inline bool piergo_call_edit_set_block_nbt(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4, int32_t a5)
{
    return api->edit_set_block_nbt(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_edit_set_block_states(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_set_block_states) + sizeof(api->edit_set_block_states)
        && api->edit_set_block_states != NULL;
}
static inline bool piergo_call_edit_set_block_states(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4, PierStr a5, int32_t a6)
{
    return api->edit_set_block_states(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_edit_set_block_entity(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_set_block_entity) + sizeof(api->edit_set_block_entity)
        && api->edit_set_block_entity != NULL;
}
static inline bool piergo_call_edit_set_block_entity(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4)
{
    return api->edit_set_block_entity(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_edit_spawn_entity_nbt(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_spawn_entity_nbt) + sizeof(api->edit_spawn_entity_nbt)
        && api->edit_spawn_entity_nbt != NULL;
}
static inline bool piergo_call_edit_spawn_entity_nbt(const PierApi* api, int32_t a0, PierStr a1, bool a2, double a3, double a4, double a5, PierActorId* a6)
{
    return api->edit_spawn_entity_nbt(a0, a1, a2, a3, a4, a5, a6);
}

static inline bool piergo_has_edit_trace_ray(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_trace_ray) + sizeof(api->edit_trace_ray)
        && api->edit_trace_ray != NULL;
}
static inline bool piergo_call_edit_trace_ray(const PierApi* api, PierActorId a0, float a1, bool a2, bool a3, void* a4, PierStrSink a5)
{
    return api->edit_trace_ray(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_lane_publish(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, lane_publish) + sizeof(api->lane_publish)
        && api->lane_publish != NULL;
}
static inline uint64_t piergo_call_lane_publish(const PierApi* api, PierModHandle a0, PierStr a1, PierLaneDesc const* a2)
{
    return api->lane_publish(a0, a1, a2);
}

static inline bool piergo_has_lane_unpublish(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, lane_unpublish) + sizeof(api->lane_unpublish)
        && api->lane_unpublish != NULL;
}
static inline bool piergo_call_lane_unpublish(const PierApi* api, PierModHandle a0, uint64_t a1)
{
    return api->lane_unpublish(a0, a1);
}

static inline bool piergo_has_lane_acquire(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, lane_acquire) + sizeof(api->lane_acquire)
        && api->lane_acquire != NULL;
}
static inline int32_t piergo_call_lane_acquire(const PierApi* api, PierModHandle a0, PierStr a1, uint64_t a2, PierLaneRef* a3)
{
    return api->lane_acquire(a0, a1, a2, a3);
}

static inline bool piergo_has_lane_release(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, lane_release) + sizeof(api->lane_release)
        && api->lane_release != NULL;
}
static inline bool piergo_call_lane_release(const PierApi* api, PierModHandle a0, uint64_t a1)
{
    return api->lane_release(a0, a1);
}

static inline bool piergo_has_lane_list(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, lane_list) + sizeof(api->lane_list)
        && api->lane_list != NULL;
}
static inline void piergo_call_lane_list(const PierApi* api, void* a0, PierStrSink a1)
{
    api->lane_list(a0, a1);
}

static inline bool piergo_has_md_list_dimensions(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_list_dimensions) + sizeof(api->md_list_dimensions)
        && api->md_list_dimensions != NULL;
}
static inline void piergo_call_md_list_dimensions(const PierApi* api, void* a0, PierStrSink a1)
{
    api->md_list_dimensions(a0, a1);
}

static inline bool piergo_has_level_delete_chunk_keys(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_delete_chunk_keys) + sizeof(api->level_delete_chunk_keys)
        && api->level_delete_chunk_keys != NULL;
}
static inline int32_t piergo_call_level_delete_chunk_keys(const PierApi* api, int32_t a0, int32_t a1, int32_t a2)
{
    return api->level_delete_chunk_keys(a0, a1, a2);
}

static inline bool piergo_has_level_chunks_loaded(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_chunks_loaded) + sizeof(api->level_chunks_loaded)
        && api->level_chunks_loaded != NULL;
}
static inline int32_t piergo_call_level_chunks_loaded(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4)
{
    return api->level_chunks_loaded(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_player_conn_id(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, player_conn_id) + sizeof(api->player_conn_id)
        && api->player_conn_id != NULL;
}
static inline uint64_t piergo_call_player_conn_id(const PierApi* api, PierPlayerSel a0)
{
    return api->player_conn_id(a0);
}

static inline bool piergo_has_level_chunk_keys(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_chunk_keys) + sizeof(api->level_chunk_keys)
        && api->level_chunk_keys != NULL;
}
static inline int32_t piergo_call_level_chunk_keys(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, void* a3, PierStrSink a4)
{
    return api->level_chunk_keys(a0, a1, a2, a3, a4);
}

static inline bool piergo_has_level_delete_key(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_delete_key) + sizeof(api->level_delete_key)
        && api->level_delete_key != NULL;
}
static inline bool piergo_call_level_delete_key(const PierApi* api, PierStr a0)
{
    return api->level_delete_key(a0);
}

static inline bool piergo_has_level_set_biome(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, level_set_biome) + sizeof(api->level_set_biome)
        && api->level_set_biome != NULL;
}
static inline int32_t piergo_call_level_set_biome(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, PierStr a5)
{
    return api->level_set_biome(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_get_extra_block(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_extra_block) + sizeof(api->get_extra_block)
        && api->get_extra_block != NULL;
}
static inline bool piergo_call_get_extra_block(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, void* a4, PierStrSink a5)
{
    return api->get_extra_block(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_set_extra_block(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, set_extra_block) + sizeof(api->set_extra_block)
        && api->set_extra_block != NULL;
}
static inline bool piergo_call_set_extra_block(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, PierStr a4, int32_t a5)
{
    return api->set_extra_block(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_get_tps(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_tps) + sizeof(api->get_tps)
        && api->get_tps != NULL;
}
static inline double piergo_call_get_tps(const PierApi* api, int32_t a0)
{
    return api->get_tps(a0);
}

static inline bool piergo_has_get_mspt(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, get_mspt) + sizeof(api->get_mspt)
        && api->get_mspt != NULL;
}
static inline double piergo_call_get_mspt(const PierApi* api, int32_t a0)
{
    return api->get_mspt(a0);
}

static inline bool piergo_has_packet_hook_register_ids(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, packet_hook_register_ids) + sizeof(api->packet_hook_register_ids)
        && api->packet_hook_register_ids != NULL;
}
static inline PierPacketHookHandle piergo_call_packet_hook_register_ids(const PierApi* api, PierModHandle a0, int32_t a1, int32_t const* a2, size_t a3, PierPacketCb a4, void* a5)
{
    return api->packet_hook_register_ids(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_scan_region_indexed(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, scan_region_indexed) + sizeof(api->scan_region_indexed)
        && api->scan_region_indexed != NULL;
}
static inline bool piergo_call_scan_region_indexed(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, void* a7, PierPaletteSink a8, PierCellSink a9)
{
    return api->scan_region_indexed(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}

static inline bool piergo_has_edit_fill_region(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_fill_region) + sizeof(api->edit_fill_region)
        && api->edit_fill_region != NULL;
}
static inline int64_t piergo_call_edit_fill_region(const PierApi* api, int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, PierStr a7, int32_t a8)
{
    return api->edit_fill_region(a0, a1, a2, a3, a4, a5, a6, a7, a8);
}

static inline bool piergo_has_edit_set_blocks(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, edit_set_blocks) + sizeof(api->edit_set_blocks)
        && api->edit_set_blocks != NULL;
}
static inline int64_t piergo_call_edit_set_blocks(const PierApi* api, int32_t a0, PierStr const* a1, uint32_t a2, PierBlockCell const* a3, size_t a4, int32_t a5)
{
    return api->edit_set_blocks(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_container_get_items(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, container_get_items) + sizeof(api->container_get_items)
        && api->container_get_items != NULL;
}
static inline bool piergo_call_container_get_items(const PierApi* api, PierContainerRef a0, void* a1, PierSlotSink a2)
{
    return api->container_get_items(a0, a1, a2);
}

static inline bool piergo_has_md_add_dimension(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_add_dimension) + sizeof(api->md_add_dimension)
        && api->md_add_dimension != NULL;
}
static inline int32_t piergo_call_md_add_dimension(const PierApi* api, PierStr a0, PierStr a1)
{
    return api->md_add_dimension(a0, a1);
}

static inline bool piergo_has_md_add_dimension_pack(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_add_dimension_pack) + sizeof(api->md_add_dimension_pack)
        && api->md_add_dimension_pack != NULL;
}
static inline int32_t piergo_call_md_add_dimension_pack(const PierApi* api, PierStr a0, PierStr a1, PierStr a2)
{
    return api->md_add_dimension_pack(a0, a1, a2);
}

static inline bool piergo_has_md_pack_inspect(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_pack_inspect) + sizeof(api->md_pack_inspect)
        && api->md_pack_inspect != NULL;
}
static inline int32_t piergo_call_md_pack_inspect(const PierApi* api, PierStr a0, void* a1, PierStrSink a2)
{
    return api->md_pack_inspect(a0, a1, a2);
}

static inline bool piergo_has_md_retire_dimension(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_retire_dimension) + sizeof(api->md_retire_dimension)
        && api->md_retire_dimension != NULL;
}
static inline bool piergo_call_md_retire_dimension(const PierApi* api, PierStr a0)
{
    return api->md_retire_dimension(a0);
}

static inline bool piergo_has_service_caller(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, service_caller) + sizeof(api->service_caller)
        && api->service_caller != NULL;
}
static inline void piergo_call_service_caller(const PierApi* api, void* a0, PierStrSink a1)
{
    api->service_caller(a0, a1);
}

static inline bool piergo_has_md_add_dimension_generated(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_add_dimension_generated) + sizeof(api->md_add_dimension_generated)
        && api->md_add_dimension_generated != NULL;
}
static inline int32_t piergo_call_md_add_dimension_generated(const PierApi* api, PierStr a0, PierStr a1, PierStr a2, PierStr a3, PierGenerateChunkFn a4, void* a5)
{
    return api->md_add_dimension_generated(a0, a1, a2, a3, a4, a5);
}

static inline bool piergo_has_md_set_dimension_cells(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, md_set_dimension_cells) + sizeof(api->md_set_dimension_cells)
        && api->md_set_dimension_cells != NULL;
}
static inline bool piergo_call_md_set_dimension_cells(const PierApi* api, int32_t a0, int32_t a1, int32_t a2)
{
    return api->md_set_dimension_cells(a0, a1, a2);
}

static inline bool piergo_has_registry_list(const PierApi* api)
{
    return api != NULL && api->struct_size >= offsetof(PierApi, registry_list) + sizeof(api->registry_list)
        && api->registry_list != NULL;
}
static inline bool piergo_call_registry_list(const PierApi* api, int32_t a0, void* a1, PierStrSink a2)
{
    return api->registry_list(a0, a1, a2);
}

#endif /* PIERGO_SLOTS_GEN_H */
