#!/usr/bin/env python3
"""embed-lang: turn `lang/*.lang` into a C++ table compiled into the host.

Why the translations are compiled in rather than read off disk.

`loadLanguages` reads `getModDir()/lang`, and getting that directory onto a server means
the packaging step has to carry it. It did not: modpacker packs the target and
`manifest.json`, `lang/` stayed in the repository, and every server ran on built-in
English. Nothing reported it, because a missing lang directory is not an error — the one
line that would have said so only prints when keys load.

A build step that copies the directory fixes that particular failure and leaves the
shape of it: the translations are only as reliable as a packaging rule nobody tests.
Compiling them in removes the question. The disk path stays, above the compiled table,
so an operator can still override a line by dropping a file — which is what that path
was actually for.

Run after editing any .lang file:

    python3 tools/embed-lang.py

`tools/checks/lang_embedded.py` fails if the generated file and the .lang files
disagree, so forgetting to run this is caught rather than silently shipping stale text.
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANGS = ROOT / "lang"
OUT = ROOT / "packages/pier-support/src/LangShipped.inc"

HEADER = """// GENERATED by tools/embed-lang.py from lang/*.lang -- do not edit by hand.
//
// Edit the .lang file and re-run the generator; tools/checks/lang_embedded.py fails
// when this file and those disagree.
//
// The translations are compiled in because a packaging rule that has to carry a data
// directory is one that can quietly not carry it, and the symptom is an English log on
// a translated server with nothing reporting why. A file on disk still overrides this
// table per key, which is what the disk path is for.
"""


def read_lang(path):
    """key -> line. Same shape readFile() accepts, so the two cannot drift."""
    out = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key:
            out[key] = value.strip()
    return out


def cxx_string(s):
    """A C++ literal. Sources are compiled with /utf-8 (xmake.lua), so the text stays
    readable rather than becoming a wall of octal escapes; only the characters that
    would end the literal need escaping."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render():
    if not LANGS.is_dir():
        raise SystemExit("lang/ is missing")
    locales = sorted(p for p in LANGS.glob("*.lang"))
    lines = [HEADER, "// clang-format off", "{"]
    for path in locales:
        entries = read_lang(path)
        lines.append(f'    {{"{path.stem}", {{')
        for key in sorted(entries):
            lines.append(f"        {{{cxx_string(key)}, {cxx_string(entries[key])}}},")
        lines.append("    }},")
    lines.append("}")
    lines.append("// clang-format on")
    return "\n".join(lines) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"  {OUT.relative_to(ROOT)} does not exist; run tools/embed-lang.py")
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(
                f"  {OUT.relative_to(ROOT)} does not match lang/*.lang; "
                "run tools/embed-lang.py"
            )
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    n = sum(len(read_lang(p)) for p in LANGS.glob("*.lang"))
    print(f"  wrote {OUT.relative_to(ROOT)}: {n} key(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
