#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen-zig-api: writes bindings/zig/src/props_gen.zig and the Zig package's copy of abi.h.

Zig calls slots through `core.slot`, so unlike Go it needs no generated layer to reach the
table. What is generated is the family of property and verb methods: one per constant of
the tables of abi.h, on Player, Entity, BlockAt and Item, with the same naming and the same
errors as the Go binding's props_gen.go. A read the host cannot answer is error.NoAnswer,
never a zero or a false.

Names that Zig reserves are escaped with @"...", and every parameter and local of the
generated code carries an underscore, which no generated method name does, so nothing it
declares can shadow anything else.

Usage:
    python3 tools/gen-zig-api.py           # write the files
    python3 tools/gen-zig-api.py --check   # exit 1 when either is stale
"""

import importlib.util
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "checks"))
from _abi import ROOT, read_abi  # noqa: E402

OUT = os.path.join(ROOT, "bindings", "zig", "src", "props_gen.zig")
ABI_SRC = os.path.join(ROOT, "packages", "pier-abi", "include", "sdk", "abi.h")
ABI_COPY = os.path.join(ROOT, "bindings", "zig", "include", "sdk", "abi.h")

ZIG_RESERVED = {
    "addrspace", "align", "allowzero", "and", "anyframe", "anytype", "asm", "async", "await",
    "break", "callconv", "catch", "comptime", "const", "continue", "defer", "else", "enum",
    "errdefer", "error", "export", "extern", "fn", "for", "if", "inline", "linksection",
    "noalias", "noinline", "nosuspend", "opaque", "or", "orelse", "packed", "pub", "resume",
    "return", "struct", "suspend", "switch", "test", "threadlocal", "try", "union",
    "unreachable", "usingnamespace", "var", "volatile", "while", "type", "bool", "void",
    "anyerror", "anyopaque", "noreturn", "isize", "usize", "true", "false", "null", "undefined",
}
# Members the fixed part of the file declares; a generated name must differ from them.
FIXED = {"byName", "byXuid", "byUuid", "cSel", "of", "at", "allocator"}


def go_gen():
    spec = importlib.util.spec_from_file_location("gen_go_api", os.path.join(os.path.dirname(__file__), "gen-go-api.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def lower_camel(words):
    parts = words.lower().split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def ident(name):
    return '@"%s"' % name if name in ZIG_RESERVED else name


# prefix, receiver, kind, slot, the arguments naming the receiver
FAMILIES = [
    ("PIER_PPROP_", "Player", "num", "player_get_num", "self.cSel()"),
    ("PIER_PSTR_", "Player", "str", "player_get_str", "self.cSel()"),
    ("PIER_PACT_", "Player", "act", "player_action", "self.cSel()"),
    ("PIER_APROP_", "Entity", "num", "actor_get_num", "self.actor_id"),
    ("PIER_ASTR_", "Entity", "str", "actor_get_str", "self.actor_id"),
    ("PIER_AACT_", "Entity", "act", "actor_action", "self.actor_id"),
    ("PIER_BPROP_", "BlockAt", "num", "block_get_num", "self.dim_id, self.pos_x, self.pos_y, self.pos_z"),
    ("PIER_BSTR_", "BlockAt", "str", "block_get_str", "self.dim_id, self.pos_x, self.pos_y, self.pos_z"),
    ("PIER_BACT_", "BlockAt", "bact", "block_action", "self.dim_id, self.pos_x, self.pos_y, self.pos_z"),
    ("PIER_IPROP_", "Item", "num", "item_get_num", "core.str(self.item_snbt)"),
    ("PIER_ISTR_", "Item", "str", "item_get_str", "core.str(self.item_snbt)"),
    ("PIER_SRV_", None, "str", "server_info_str", ""),
    ("PIER_SYS_", None, "str", "sys_info_str", ""),
]

HEAD = '''//! props_gen.zig: one method per property and verb of the constant tables of abi.h.
//! Generated by tools/gen-zig-api.py; edit the generator, not this file.

const std = @import("std");
const core = @import("core.zig");

/// How a Player selector names its player. A decision about permissions, money or ownership
/// keys on the xuid: a name can change hands.
pub const SelKind = enum(i32) { name = 0, xuid = 1, uuid = 2 };
'''

TYPES = {
    "Player": '''
/// One player, named by a selector.
pub const Player = struct {
    sel_kind: SelKind,
    sel_value: []const u8,

    pub fn byName(sel_name: []const u8) Player {
        return .{ .sel_kind = .name, .sel_value = sel_name };
    }

    pub fn byXuid(sel_xuid: []const u8) Player {
        return .{ .sel_kind = .xuid, .sel_value = sel_xuid };
    }

    pub fn byUuid(sel_uuid: []const u8) Player {
        return .{ .sel_kind = .uuid, .sel_value = sel_uuid };
    }

    pub fn cSel(self: Player) core.c.PierPlayerSel {
        return .{ .kind = @intFromEnum(self.sel_kind), .value = core.str(self.sel_value) };
    }
''',
    "Entity": '''
/// One actor, named by its unique id, the uid of event payloads.
pub const Entity = struct {
    actor_id: i64,

    pub fn of(actor_id_value: i64) Entity {
        return .{ .actor_id = actor_id_value };
    }
''',
    "BlockAt": '''
/// One block cell of a dimension.
pub const BlockAt = struct {
    dim_id: i32,
    pos_x: i32,
    pos_y: i32,
    pos_z: i32,

    pub fn at(at_dim: i32, at_x: i32, at_y: i32, at_z: i32) BlockAt {
        return .{ .dim_id = at_dim, .pos_x = at_x, .pos_y = at_y, .pos_z = at_z };
    }
''',
    "Item": '''
/// An item stack as SNBT, a value: reading it asks the host about that SNBT.
pub const Item = struct {
    item_snbt: []const u8,

    pub fn of(item_snbt_value: []const u8) Item {
        return .{ .item_snbt = item_snbt_value };
    }
''',
}


def render():
    g = go_gen()
    members = g.enum_members(read_abi())
    by_type, free = {t: [] for t in TYPES}, []
    used = {t: set(FIXED) for t in list(TYPES) + [None]}
    for prefix, recv, kind, slot, args in FAMILIES:
        fam = [(n, d) for n, v, d in members if n.startswith(prefix)]
        if not fam:
            raise SystemExit("no constant starts with %s" % prefix)
        for n, doc in fam:
            base = lower_camel(n[len(prefix):])
            name = base
            if recv is None:
                name = lower_camel(prefix[len("PIER_"):-1] + "_" + n[len(prefix):])
            if kind == "str" and name in used[recv]:
                name += "Text"
            if kind in ("act", "bact") and name in used[recv]:
                name += "Action"
            if name in used[recv] or "_" in name:
                raise SystemExit("%s.%s would be declared twice or could shadow a local" % (recv, name))
            used[recv].add(name)
            doc = doc or n
            lead = "args, " if args else ""
            lines = ["    /// %s: %s" % (n, doc)]
            if recv is None:
                lines = ["/// %s: %s" % (n, doc)]
            if kind == "num":
                is_bool = re.match(r"^(is|has|can)[A-Z]", base) is not None
                rt = "bool" if is_bool else "f64"
                lines += [
                    "    pub fn %s(self: %s) core.Error!%s {" % (ident(name), recv, rt),
                    '        const slot_fn = core.slot("%s") orelse return error.NotProvided;' % slot,
                    "        var out_value: f64 = 0;",
                    "        if (!slot_fn(%s, core.c.%s, &out_value)) return error.NoAnswer;" % (args, n),
                    "        return %s;" % ("out_value != 0" if is_bool else "out_value"),
                    "    }",
                ]
                if recv == "Player" and "(S)" in doc:
                    sname = "set" + base[:1].upper() + base[1:]
                    if sname in used[recv]:
                        raise SystemExit("Player.%s would be declared twice" % sname)
                    used[recv].add(sname)
                    lines += [
                        "",
                        "    /// Writes %s: %s" % (n, doc),
                        "    pub fn %s(self: Player, new_value: f64) core.Error!void {" % ident(sname),
                        '        const slot_fn = core.slot("player_set_num") orelse return error.NotProvided;',
                        "        if (!slot_fn(self.cSel(), core.c.%s, new_value)) return error.Refused;" % n,
                        "    }",
                    ]
            elif kind == "str":
                ind = "" if recv is None else "    "
                head = ("pub fn %s(allocator: std.mem.Allocator) core.Error![]u8 {" % ident(name)) if recv is None \
                    else ("pub fn %s(self: %s, allocator: std.mem.Allocator) core.Error![]u8 {" % (ident(name), recv))
                call_args = ("core.c.%s" % n) if recv is None else ("%s, core.c.%s" % (args, n))
                lines += [
                    ind + head,
                    ind + '    const slot_fn = core.slot("%s") orelse return error.NotProvided;' % slot,
                    ind + "    var col = core.Collector.init(allocator);",
                    ind + "    defer col.deinit();",
                    ind + "    if (!slot_fn(%s, &col, &core.Collector.sink)) return error.NoAnswer;" % call_args,
                    ind + "    return col.take();",
                    ind + "}",
                ]
            else:
                params = "s_arg: []const u8" if kind == "bact" else "s_arg: []const u8, n_a: f64, n_b: f64, n_c: f64"
                cargs = "core.str(s_arg)" if kind == "bact" else "core.str(s_arg), n_a, n_b, n_c"
                lines += [
                    "    ///",
                    "    /// The output, when the verb has one, is returned; abi.h names each argument.",
                    "    pub fn %s(self: %s, allocator: std.mem.Allocator, %s) core.Error![]u8 {" % (ident(name), recv, params),
                    '        const slot_fn = core.slot("%s") orelse return error.NotProvided;' % slot,
                    "        var col = core.Collector.init(allocator);",
                    "        defer col.deinit();",
                    "        if (!slot_fn(%s, core.c.%s, %s, &col, &core.Collector.sink)) return error.Refused;" % (args, n, cargs),
                    "        return col.takeOrEmpty();",
                    "    }",
                ]
            (free if recv is None else by_type[recv]).append("\n".join(lines))
    out = [HEAD]
    for t, text in TYPES.items():
        out.append(text)
        out.append("\n\n".join(by_type[t]))
        out.append("};\n")
    out.append("\n".join(free and ["\n" + "\n\n".join(free)]))
    text = "\n".join(out)
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip("\n") + "\n"
    return text, sum(len(v) for v in by_type.values()) + len(free)


def read_bytes(path):
    if not os.path.exists(path):
        return b""
    with open(path, "rb") as f:
        return f.read()


def main():
    text, n = render()
    if "--check" in sys.argv:
        bad = 0
        if (open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else "") != text:
            print("props_gen.zig is stale against abi.h; run python3 tools/gen-zig-api.py")
            bad = 1
        if read_bytes(ABI_COPY) != read_bytes(ABI_SRC):
            print("bindings/zig/include/sdk/abi.h differs from the header; run python3 tools/gen-zig-api.py")
            bad = 1
        if not bad:
            print("props_gen.zig and the abi.h copy match the header (%d method(s))" % n)
        return bad
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.makedirs(os.path.dirname(ABI_COPY), exist_ok=True)
    with open(ABI_COPY, "wb") as f:
        f.write(read_bytes(ABI_SRC))
    print("wrote %s: %d method(s), and the abi.h copy" % (os.path.relpath(OUT, ROOT), n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
