#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen-go-slots: writes bindings/go/levilamina/slots_gen.h from sdk/abi.h.

Go cannot call a C function pointer, so the Go binding reaches every slot of PierApi through
a C function that does it: `piergo_call_<slot>(api, args...)` forwards to `api-><slot>`, and
`piergo_has_<slot>(api)` applies both gates of contract §10, that `struct_size` covers the
slot and that it is not NULL. The table itself is not mirrored: cgo includes abi.h, so the C
compiler lays it out, which is the strongest form of "read abi.h only" a binding can take.

The header is generated rather than written because it has one entry per slot and the
signatures must match abi.h exactly; `--check` regenerates it in memory and fails when the
file on disk differs, which is what the `go-slots-current` check runs.

Usage:
    python3 tools/gen-go-slots.py           # write the header
    python3 tools/gen-go-slots.py --check   # exit 1 when the header is stale
"""

import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "checks"))
from _abi import ROOT, read_abi, strip_comments, struct_body  # noqa: E402

OUT = os.path.join(ROOT, "bindings", "go", "levilamina", "slots_gen.h")
# The Go module root is bindings/go, and `go get` fetches nothing above it, so the package
# carries its own copy of abi.h. The copy is the header byte for byte, which --check verifies.
ABI_SRC = os.path.join(ROOT, "packages", "pier-abi", "include", "sdk", "abi.h")
ABI_COPY = os.path.join(ROOT, "bindings", "go", "levilamina", "include", "sdk", "abi.h")

C_WORDS = {"void", "char", "short", "int", "long", "float", "double", "signed", "unsigned",
           "bool", "_Bool", "const", "volatile", "struct", "enum", "size_t"}


def type_names(src):
    """Every name abi.h defines as a type, so a parameter ending in one is unnamed."""
    # No brace inside the match: `typedef struct X { int32_t x; ...` would otherwise read the
    # field name x as a type, and every parameter named x would lose its rename.
    names = set(re.findall(r"typedef\s+[^;{}]*?\b(\w+)\s*;", src))
    names |= set(re.findall(r"typedef\s+[^;(]*\(\s*\*\s*(\w+)\s*\)", src))
    names |= set(re.findall(r"\}\s*(\w+)\s*;", src))
    return names


def split_top(params):
    out, depth, cur = [], 0, ""
    for ch in params:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def rename(param, index, types):
    """The parameter declared with the name a<index>, whatever name abi.h gave it."""
    name = "a%d" % index
    fp = re.search(r"\(\s*\*\s*(\w*)\s*\)", param)
    if fp:
        return param[:fp.start()] + "(*" + name + ")" + param[fp.end():]
    m = re.match(r"^(.*?[\s\*])(\w+)$", param)
    if m and m.group(2) not in types and m.group(2) not in C_WORDS \
            and not m.group(2).endswith("_t") and re.search(r"\w", m.group(1)):
        return m.group(1).rstrip() + " " + name if not m.group(1).endswith("*") \
            else m.group(1) + name
    return param + " " + name


def slots(src):
    types = type_names(src)
    body = strip_comments(struct_body(src, "PierApi"))
    out = []
    for decl in body.split(";"):
        decl = " ".join(decl.split())
        m = re.match(r"^(.+?)\(\s*\*\s*(\w+)\s*\)\s*\((.*)\)$", decl)
        if not m:
            continue
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3).strip()
        plist = [] if params in ("", "void") else split_top(params)
        out.append((ret, name, [rename(p, i, types) for i, p in enumerate(plist)]))
    return out


def render(src):
    lines = [
        "/* slots_gen.h: one forwarding function and one gate per PierApi slot, for cgo.",
        " * Generated by tools/gen-go-slots.py from sdk/abi.h; edit the generator, not this. */",
        "#ifndef PIERGO_SLOTS_GEN_H",
        "#define PIERGO_SLOTS_GEN_H",
        "",
        "#include <stddef.h>",
        "",
        "#include \"sdk/abi.h\"",
        "",
    ]
    for ret, name, params in slots(src):
        lines.append("static inline bool piergo_has_%s(const PierApi* api)" % name)
        lines.append("{")
        lines.append("    return api != NULL && api->struct_size >= offsetof(PierApi, %s) + sizeof(api->%s)"
                     % (name, name))
        lines.append("        && api->%s != NULL;" % name)
        lines.append("}")
        args = ", ".join("a%d" % i for i in range(len(params)))
        plist = ", ".join(["const PierApi* api"] + params)
        lines.append("static inline %s piergo_call_%s(%s)" % (ret, name, plist))
        lines.append("{")
        lines.append("    %sapi->%s(%s);" % ("" if ret == "void" else "return ", name, args))
        lines.append("}")
        lines.append("")
    lines.append("#endif /* PIERGO_SLOTS_GEN_H */")
    return "\n".join(lines) + "\n"


def read_bytes(path):
    if not os.path.exists(path):
        return b""
    with open(path, "rb") as f:
        return f.read()


def main():
    text = render(read_abi())
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        bad = 0
        if current != text:
            print("slots_gen.h is stale against abi.h; run python3 tools/gen-go-slots.py")
            bad = 1
        if read_bytes(ABI_COPY) != read_bytes(ABI_SRC):
            print("bindings/go/levilamina/include/sdk/abi.h differs from the header; run "
                  "python3 tools/gen-go-slots.py")
            bad = 1
        if not bad:
            print("slots_gen.h and the abi.h copy match the header (%d slot(s))"
                  % len(slots(read_abi())))
        return bad
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    os.makedirs(os.path.dirname(ABI_COPY), exist_ok=True)
    with open(ABI_COPY, "wb") as f:
        f.write(read_bytes(ABI_SRC))
    print("wrote %s with %d slot(s)" % (os.path.relpath(OUT, ROOT), len(slots(read_abi()))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
